### ISSUE TITLE
Directory where browserify is executed

### ISSUE THREAD

**Issue by Jerskouille** [browserify-rails/browserify-rails#100]
Hi,

I couldn't find out where the browserify command was launched. I would have assumed `Rails.root` or `app/assets/javascripts` or `public/assets`, but it doesn't seem like it.
I'm using [`vueify`](https://github.com/vuejs/vueify), which uses a config file that should be where browserify is launched.

Thanks in advance!

**Comment by cymen** [comment]
It runs the browserify that is installed by npm/node. So you put a package.json in the root of your rails project and then install browserify. So it'll end up in `node_modules/browserify/...` off of the root of your Rails project. The gem expects it to be there and executes it by looking there.

**Comment by cymen** [comment]
For vueify, you would add the transform just like the other transforms mentioned in the README.

**Comment by Jerskouille** [comment]
It didn't work, so I went ahead and added some output to print the value of base directory and found https://github.com/browserify-rails/browserify-rails/blob/63566f1759cf6f0680d4ba15b999cde13b4e970a/lib/browserify-rails/browserify_processor.rb#L171-L174 .
Outputting `base_directory` shows that it is run from the the path of the main file, so in my case it was in `app/assets/javascript/home`.
Anyway, thanks for this gem, and for trying to help !

**Comment by cymen** [comment]
Ah, sorry, I was confused what you were asking about -- glad you got it figured out (makes sense now).

**Comment by Jerskouille** [comment]
Don't worry, I actually should have done this in the first place. :)
But it might help someone to have the answer here.
