### ISSUE TITLE
Possible to avoid "relative paths hell" with browserify-rails?

### ISSUE THREAD

**Issue by dnewkerk** [browserify-rails/browserify-rails#102]
I'm attempting to follow the advice at https://github.com/greypants/gulp-starter/issues/17 to avoid what seems to have been labeled "relative paths hell". For instance requiring a module from another module deep within my directory structure currently looks something like this: require('../../../../../../../common/my-module'); If I decide to require my-module from some other file, I can't just write a simple require statement or even copy and paste that line into the new file, but rather have to carefully count how many directory levels I have to traverse from the new context. I'd much prefer to write require('common/my-module'); from any context and call it a day :)

The above mentioned solution involves gulp, which of course we're not using in the case of browserify-rails. I've seen the browserify documentation that recommends putting your own code in node_modules, though that's not an option in my case.

However, I'm not sure how to get this working with browserify-rails. I've made various attempts with config.browserify_rails.commandline_options but so far haven't been able to get it working. Has anyone else solved this issue in the context of browserify-rails? Thanks in advance for any advice!

**Comment by cymen** [comment]
You will have problems trying to do that with this gem -- it's hard enough getting it to work with the asset pipeline. You are of course free to do what you will.

On a side note, IMHO, relative paths are not a problem.

**Comment by dnewkerk** [comment]
Thanks for the reply, good to know.

**Comment by cymen** [comment]
@dnewkerk I updated my reply slightly -- I wanted to be clear I think it'll be problematic for technical reasons, not related to my opinion.

I do think it would work if you make your own require. I don't know all of the details for that but it should be possible and I don't want to discourage you from doing that.

**Comment by chinshr** [comment]
@dnewkerk did you find a workaround to do stuff like this? 

`import MyComponent from 'components';`
