### ISSUE TITLE
Uncaught ReferenceError: require is not defined

### ISSUE THREAD

**Issue by kremez19** [browserify-rails/browserify-rails#103]
After rake assets:precompile I've restart rails server and see the error:
```
Uncaught ReferenceError: require is not defined
```

In development all works fine, issue happen only with compiled assets.

**Comment by cymen** [comment]
Is browserify-rails included in your `:production` group in the Gemfile? It needs to be there for asset compilation (so it won't actually be involved beyond the compilation).

**Comment by dang-hoang-hieu** [comment]
@cymen I also get this error! 

Browserify-rails is installed on `staging` server, It successfully compiled to a js file but its content include only 1 entry line ex: `App = require('path_to_my_app_file');`
In development all works fine!

thanks

**Comment by kremez19** [comment]
@cymen yes, browserify-rails is included in global gem group. And it also doesn't work in staging env as well.

**Comment by kremez19** [comment]
On my project I've finished with deleting browserify-rails gem, move all top level require to app.js.jsx, that start my react application and add scripts config like below to package.json
```json
"scripts": {
    "bundle": "browserify app/assets/javascripts/app.js.jsx -o app/assets/javascripts/bundle.js --transform babelify",
    "watch-js": "watchify app/assets/javascripts/app.js.jsx -o app/assets/javascripts/bundle.js --transform babelify",
    "start": "npm run watch-js & bundle exec puma config.ru"
}
``` 
and in appication.js I just add 

```js
//= require bundle
```

**Comment by cymen** [comment]
@kremez19 Great -- if that works for you, :+1:. I think this gem is best for legacy non-CommonJS code and fully support using whatever works.

@dang-hoang-hieu I'd install this gem in a vanilla Rails and see if it works -- if it does, work backwards to figure out what part of your config is an issue.

**Comment by dang-hoang-hieu** [comment]
@kremez19 
In case of not using browserify-rails, my opinion is no need `npm run watch-js` at all! if you use any build automation like `Wercker`, you can pre-build `jsx` to `bundle.js` with Wercker. You dont have to install nodejs and share resources to watchify in production and staging servers.

**Comment by dang-hoang-hieu** [comment]
@cymen thanks in advance!

**Comment by cymen** [comment]
@dang-hoang-hieu I would also double check your config for browserify-rails is present in the environment file -- it's easy to accidentally only configure it in say development.rb and not the other environments.

**Comment by dang-hoang-hieu** [comment]
@cymen I have this in my staging.rb
```
config.browserify_rails.commandline_options = "-t reactify -t uglifyify"
```

**Comment by cymen** [comment]
@dang-hoang-hieu Can you try version 1.3.0 -- I just released it with a change as described in issue https://github.com/browserify-rails/browserify-rails/issues/105. It may be unrelated.

**Comment by rpearce** [comment]
I think this is what you need in your `package.json` to fix this issue:
```
  "browserify": {
    "transform": [
      [
        "reactify"
      ]
    ]
  },
```
Using `browserify-rails`' command line option happens too late in the chain for `reactify`, as there is some npm module that needs this transform early on. I'm not 100% sure of the source of the issue, but this has been working for me across projects.

Also, I've found if you're using the reactify transform with `browserify-rails`, don't include any JSX in `application.js`. Instead, have `application.js` require a file, perhaps named `browser.js`, that loads your JSX/React on the page.

**Comment by dang-hoang-hieu** [comment]
@cymen @rpearce 
thanks, I will give it a try, I am currently so busy!

**Comment by cymen** [comment]
I will close this for now assuming all works as expected.

**Comment by guillewu** [comment]
I'm getting`Uncaught ReferenceError: require is not defined` error when requiring a module with inline coffeescript in a view. Any ideas what might be causing it? Thanks in advance!
