### ISSUE TITLE
Cannot install gem version 0.9.2

### ISSUE THREAD

**Issue by kockok** [browserify-rails/browserify-rails#104]
``Could not find gem 'browserify-rails (= 0.9.2) ruby' in any of the gem sources listed in your Gemfile or       installed on this machine.``

however, when I bundle 0.9.3, it depends on sprockets 2.12.4
``Using sprockets 2.12.4
Using browserify-rails 0.9.3``

Please advise.

**Comment by cymen** [comment]
Is there a reason you can't use latest (1.2.0)?

**Comment by kockok** [comment]
Sorry, didn't read the change log.

just read the latest `Bump version to 0.9.2	2 months ago` and thought that is the newest version.

**Comment by cymen** [comment]
No problem, good luck!
