### ISSUE TITLE
Issue with `tilt` being a development dependency

### ISSUE THREAD

**Issue by rpearce** [browserify-rails/browserify-rails#105]
Hello from The Iron Yard Charleston's Rails class! 

We <3 `browserify-rails`, but think we may have found an issue. [This line of code](https://github.com/browserify-rails/browserify-rails/blob/master/browserify-rails.gemspec#L32) in the `.gemspec` file:
```ruby
spec.add_development_dependency "tilt"
```
we believe creates an issue in `production` when a Rails app has `coffee-rails` and `sass-rails` included as `dev`/`test` dependencies in a Gemfile. Here is the stack trace:
```
/app/vendor/bundle/ruby/2.2.0/gems/browserify-rails-1.2.0/lib/browserify-rails/browserify_processor.rb:1:in `require': cannot load such file -- tilt (LoadError)
	from /app/vendor/bundle/ruby/2.2.0/gems/browserify-rails-1.2.0/lib/browserify-rails/browserify_processor.rb:1:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.2.0/gems/browserify-rails-1.2.0/lib/browserify-rails.rb:4:in `require'
	from /app/vendor/bundle/ruby/2.2.0/gems/browserify-rails-1.2.0/lib/browserify-rails.rb:4:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.2.0/gems/bundler-1.9.7/lib/bundler/runtime.rb:76:in `require'
	from /app/vendor/bundle/ruby/2.2.0/gems/bundler-1.9.7/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
	from /app/vendor/bundle/ruby/2.2.0/gems/bundler-1.9.7/lib/bundler/runtime.rb:72:in `each'
	from /app/vendor/bundle/ruby/2.2.0/gems/bundler-1.9.7/lib/bundler/runtime.rb:72:in `block in require'
	from /app/vendor/bundle/ruby/2.2.0/gems/bundler-1.9.7/lib/bundler/runtime.rb:61:in `each'
	from /app/vendor/bundle/ruby/2.2.0/gems/bundler-1.9.7/lib/bundler/runtime.rb:61:in `require'
	from /app/vendor/bundle/ruby/2.2.0/gems/bundler-1.9.7/lib/bundler.rb:134:in `require'
	from /app/config/application.rb:7:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:141:in `require'
	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:141:in `require_application_and_environment!'
	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:67:in `console'
	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:8:in `require'
	from bin/rails:8:in `<main>'
```
This could have easily been overlooked, for Rails comes with `sass-rails` and `coffee-rails` outside of the dev/test Gemfile groups, but given we (and many folks) precompile our assets, we have no need of CoffeeScript nor Sass in production.

To recreate this, simply move `sass-rails` and `coffee-rails` in to the dev group in your Gemfile, and you will find that `tilt` is no longer `require`able.

We believe the fix for this would be to include `tilt` as a dependency--not just a dev one.

Of course, we could be doing something totally wrong, but we fixed this by adding
```ruby
gem 'tilt'
```
to our Gemfile _outside_ of any specific grouping.

Cheers,
TIY Charleston Ruby class

**Comment by cymen** [comment]
Thank you very much for the bug report. There were some other issues reported with less detail that I suspect are due to this issue too. I added `tilt` as a runtime dependency in the `gemspec` and released version 1.3.0 with that change. Can you confirm this fixes the issue for you (and you no longer need to require `tilt` in your Gemfile)?

Thanks again!

**Comment by rpearce** [comment]
Given `sass-rails` depends on `tilt ~> 1.1`, what would you recommend?
```
Bundler could not find compatible versions for gem "tilt":
  In Gemfile:
    browserify-rails (= 1.3.0) ruby depends on
      tilt (>= 2.0.1) ruby

    sass-rails (~> 5.0) ruby depends on
      tilt (~> 1.1) ruby
```
and here is our `Gemfile` (note: this app was created today, so this is latest everything)
```ruby
source 'https://rubygems.org'
ruby '2.2.2'

gem 'rails', '4.2.3'
gem 'browserify-rails', '1.3.0'
gem 'jbuilder', '~> 2.0'
gem 'pg'
#gem 'tilt'

group :development, :test do
  gem 'coffee-rails', '~> 4.1.0'
  gem 'pry'
  gem 'sass-rails', '~> 5.0'
  gem 'spring'
  gem 'uglifier', '>= 1.3.0'
  gem 'web-console', '~> 2.0'
end
```

**Comment by cymen** [comment]
@rpearce The odd thing is sass-rails gemspec doesn't add a dependency on tilt at all:

https://github.com/rails/sass-rails/blob/master/sass-rails.gemspec

In your Gemfile.lock, does it show what is requiring tilt ~> 1.1? I don't see it on the 3.3.x release of the sass gem itself either:

https://github.com/sass/sass/blob/e267c436bd949d4ba404ba719b029701c96fa95e/sass.gemspec

So not sure where it is coming from.

**Comment by cymen** [comment]
Looks like sass-rails got rid of tilt dependency within the last 14 days: https://github.com/rails/sass-rails/commit/0789405af097e6dd527ace6bc9bf4e8dfc354833

**Comment by cymen** [comment]
Actually, this is the right commit: https://github.com/rails/sass-rails/commit/5e09809904553a20ae836c2ca4127d90622212f8

**Comment by cymen** [comment]
So for compatibility, we can use `s.add_dependency 'tilt',            '>= 1.1', '< 3'`.

**Comment by rpearce** [comment]
Interesting. I guess it hasn't been released? It's still listed here:
https://rubygems.org/gems/sass-rails/versions/5.0.3

**Comment by rpearce** [comment]
Do we need the `< 3`?

**Comment by cymen** [comment]
I'm not sure why they have the `< 3` -- probably just future proofing. I cargo-culted it over for now. I'd also like to remove the dependency on tilt and reading how sass-rails did it will hopefully be useful!

Can you try browserify-rails v1.4.0? It should now be compatible with currently released sass-rails.

**Comment by rpearce** [comment]
Works like a charm.

**Comment by cymen** [comment]
Excellent! Thanks for confirming.
