### ISSUE TITLE
conflict with i18next library

### ISSUE THREAD

**Issue by seoyoochan** [browserify-rails/browserify-rails#108]
when I start using `browserify-rails` gem, the library from `i18next.com` does not work.
I could not figure out the problems, so my workaround was using `i18n-js` gem instead of it.
is there anyone who has the same experience?

**Comment by morenoh149** [comment]
More details are needed. Did you use npm to install `i18next` or did you include the .js file?

Interestingly as well the [main page](http://i18next.com/) lists an alternative install for browserify `npm install i18next-client` try that.

**Comment by seoyoochan** [comment]
@morenoh149 I actually just downloaded the zip file and used `i18next-1.10.1.min.js`. I already tried `npm install i18next-client` before. but neither of them worked.

**Comment by cymen** [comment]
For i18n, it is useful to remember not all of the browsers support it well. Was it working in Chrome but not Safari/IE? If so, a polyfill is needed for the missing features.

What does "does not work" mean?

**Comment by seoyoochan** [comment]
@cymen  I meant it as i18n didn't work since I have used browserify-rails together. the browser I tested with was the latest Chrome.

**Comment by cymen** [comment]
Closing as not sure what to do -- please reopen if can share a failing example rails repo.
