### ISSUE TITLE
CoffeeScript instructions recommend ".js.coffee" but this is no longer standard

### ISSUE THREAD

**Issue by jezstephens** [browserify-rails/browserify-rails#109]
The instructions in the README say to use the "standard" `.js.coffee` extension for CoffeeScript files, but since Sprockets 3 it is recommended to use just `.coffee` ([source](https://github.com/rails/sprockets/blob/master/UPGRADING.md#prefer-just-foocoffee-and-fooscss)).

Unfortunately I don't know enough about sprockets-rails yet to know what problems this might cause, if any.

**Comment by cymen** [comment]
I hesitate to do anything without a problem.

**Comment by cymen** [comment]
But patches are welcomed!

**Comment by jezstephens** [comment]
I'm not actually using this gem - I just spotted this while scanning the docs. I think it may cause confusion since Sprockets itself advises against ".js.coffee" nowadays. It does still work though. Feel free to close if you wish.

**Comment by cymen** [comment]
Cool -- I'll close. I personally do not use CoffeeScript at all so...
