### ISSUE TITLE
typescript support using tsify

### ISSUE THREAD

**Issue by rosendi** [browserify-rails/browserify-rails#110]
How can I get to work tsify with browserify-rails?

I've added tsify dependency to `package.json` and in my `application.rb`:

 `config.browserify_rails.commandline_options = "-p [tsify --module commonjs --target es5 --noImplicitAny --experimentalDecorators --extension=\".js.ts\"]"`

But it doesn't work:

```
Error while running `/Projects/angular2/node_modules/.bin/browserifyinc -p [tsify --module commonjs --target es5 --noImplicitAny --experimentalDecorators --extension=".js.ts"] --list --cachefile=/Projects/angular2/tmp/cache/browserify-rails/browserifyinc-cache.json -o "/Projects/angular2/tmp/cache/browserify-rails/output20150921-63263-1f555w5" -`:

fs.js:844
  return binding.lstat(pathModule._makeLong(path));
                                  ^

Error: ENOENT: no such file or directory, lstat '/Projects/angular2/app/assets/javascripts/_stream_0.js'
    at Error (native)
    at Object.fs.lstatSync (fs.js:844:18)
    at Object.realpathSync (fs.js:1438:21)
    at /Projects/angular2/node_modules/tsify/index.js:50:38
    at Array.map (native)
    at DestroyableTransform.flush [as _flush] (/Projects/angular2/node_modules/tsify/index.js:50:6)
    at DestroyableTransform.<anonymous> (/Projects/angular2/node_modules/tsify/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:123:12)
    at DestroyableTransform.g (events.js:260:16)
    at emitNone (events.js:67:13)
    at DestroyableTransform.emit (events.js:166:7)
```

**Comment by cymen** [comment]
You might try the approach of putting it inside of the package.json browserify configuration. I don't have a solid example of that but it seems like there are a bunch of different ways to configure browserify and that is one direction to try.

**Comment by rosendi** [comment]
TypeScript compiler can't take input through stdin and as a result tsify too. Is there any reason why browserify-rails use stdin instead of input filepath?

Please, look at my commit https://github.com/rosendi/browserify-rails/commit/4ddec5fda911ad3d229b1d130b390827141e594b. Now all works, but some tests should be fixed.

**Comment by cymen** [comment]
browserify-rails needs to use stdin because that is what the asset pipe gives us -- directives like `//= require ...` are fulfilled/resolved before it comes to browserify-rails.

**Comment by cymen** [comment]
In other words, if you aren't using what the asset pipeline gives us, it makes more sense to run browserify directly (not as part of the asset pipeline). My opinion is browserify-rails is a great way to get from non-CommonJS JavaScript to JS that uses CommonJS and then the project is at a good point to jump off to using non-asset pipeline JS compilation (ie browserify or webpack directly).

Everyone is of course to use browserify-rails as they wish.

I'm not sure how to solve the issue with typescript though.

**Comment by rosendi** [comment]
I agree. I moved from rails asset pipeline to gulp + browserify + watchify since the build process had been very slowly. Thank you for your response
