### ISSUE TITLE
Acceptance Testing and Compilation Delay

### ISSUE THREAD

**Issue by posgarou** [browserify-rails/browserify-rails#112]
I'm having problems running acceptance tests (Cucumber/Capybara) with browserify-rails.

First, a bit of background.  I have multiple JS files listed in `config/initializers/assets.rb` set to precompile.  These files include, via Sprockets requires, several files that use browserify-rails.

The issue I'm having is that Capybara gives up on tests before browserify-rails has finished running over the files.  (It took me forever to figure out that that was what the problem was.)

Two workarounds I've found:

1. Precompile assets before acceptance tests and serve those.
2. Wrap tests that would involve loading another JS file with `using_wait_time 30 do ... end`.

I'm not crazy about either of these options.  That said:

1. Is there a better solution to this problem that I'm missing?
2. If not, this info should be in the README.  I'll put in a PR for this, in that case, if you like.

**Comment by cymen** [comment]
I'd recommend the precompile approach. Updates to the README welcomed of course!

The reason I'd opt towards precompile is that the time to compile varies by project size so it would be annoying to add some arbitrary wait time and then find out the project got to big and that is why tests are mysteriously failing.

On a side note, while you are free to use browserify-rails as you see fit, you may find yourself wanting to get out of the Rails asset pipeline if your JavaScript is going to grow large. I see the best use of this project to get from non-CommonJS / non-modular code to CommonJS. Once you're there, there are more options (using browserify/webpack directly, etc). It's just something to think about if you start hitting major performance problems with this gem. Of course, improvements are very welcome too.

**Comment by posgarou** [comment]
That's probably a good point on the wait time.  A max wait time of 30 seconds would (hopefully) cover most compile times, but I suppose there will inevitably be some that take longer than that.

And I agree completely on your last point about mixing the two.  One of these days I'll fix the configuration.  :+1:
