### ISSUE TITLE
OS X 10.11 - El Capitan - env: node: No such file or directory

### ISSUE THREAD

**Issue by noelblaschke** [browserify-rails/browserify-rails#117]
Following the instruction throws a BrowserifyRails::BrowserifyError on a clean El Capitan installation:

```
=> env: node: No such file or directory
```

Changing the shebang from
```
#!/usr/bin/env node
```
to:
```
#!/usr/local/bin/node
```

in project/node_modules/.bin/browserify and project/node_modules/.bin/browserifyinc will do the thing.

Anyway this shouldn't be the best solution. So what am I doing wrong?

I used Homebrew to install node with:
```
$ brew update
$ brew install node
```

As of El Capitan /usr/bin/ is now rootless, so Homebrew creates symlinks at /usr/local/bin. I already added /usr/local/bin to my $PATH and this is also available in /usr/bin/env.

```
$ /usr/bin/env
...
=> PATH=...:/usr/local/bin:...
... 

$ which node
=> /usr/local/bin/node
```

Best regards

**Comment by cymen** [comment]
That sounds like a bug in browserfyinc. Have you filed an issue on it? It's here:

https://github.com/jsdf/browserify-incremental

**Comment by cymen** [comment]
I tried a new rails install and didn't run into this issue. I'm using node 5.0.0. Are you still having problems?

**Comment by cymen** [comment]
(please reopen if this is still an issue)

**Comment by nextofsearch** [comment]
Hi, I am suffering from the same issue.

I am deploying to Mac OS Sierra (10.12.3), which I am not sure will make difference with other linux system.

**Comment by deniskrop** [comment]
I am having this issue as well. Looks like the fix might be to install without brew

**Comment by sleepdefic1t** [comment]
```
sudo ln -s /usr/bin/nodejs /usr/bin/node
