### ISSUE TITLE
application.js with require() call refers to uninstalled NPM module

### ISSUE THREAD

**Issue by Fritzinger** [browserify-rails/browserify-rails#118]
I've been trying to add `formsy-react` and `formsy-react-components` to my rails/react app. When I started having problems I uninstalled `formsy-react-components` and just tried to get the app to see `formsy-react`. Now when I inspect my application.js generated source with the chrome developer tools, I see that the IIFE generated by browserify still refers to `formsy-react-components`.

Application.js source:

    window.Formsy = require('formsy-react');

Offending line in generated source as viewed in developer tools:

    ...
    "/Users/me/myproject/node_modules/react/react.js":[function(require,module,exports){
    arguments[4]["/Users/me/myproject/node_modules/formsy-react-components/node_modules/react/react.js"][0].apply(exports,arguments)
    ...

`formsy-react-components` is gone from node_modules:

    myproject$ ll node_modules
    total 0
    drwxr-xr-x  12 me  staff   408B 30 Oct 11:08 .
    drwxr-xr-x  33 me  staff   1.1K 30 Oct 10:58 ..
    drwxr-xr-x   4 me  staff   136B 27 Oct 17:17 .bin
    drwxr-xr-x   9 me  staff   306B 27 Oct 15:16 babelify
    drwxr-xr-x  13 me  staff   442B 27 Oct 17:17 browserify
    drwxr-xr-x  10 me  staff   340B 17 Oct 03:35 browserify-incremental
    drwxr-xr-x  10 me  staff   340B 29 Oct 10:17 coffee-reactify
    drwxr-xr-x  11 me  staff   374B 27 Oct 13:57 coffeeify
    drwxr-xr-x  19 me  staff   646B 30 Oct 10:58 formsy-react
    drwxr-xr-x   9 me  staff   306B 27 Oct 17:23 react
    drwxr-xr-x   6 me  staff   204B 30 Oct 10:11 simplest_module
    drwxr-xr-x   9 me  staff   306B 29 Oct 16:39 startinterval

No occurence of formsy-react-components anywhere in the project hierarchy:

    myproject $ find . -name formsy-react-components
    myproject $

I have ticked the disable cache option in chrome developer tools. I cleared out `public/assets` too:

    myproject $ ll public/assets
    total 0
    drwxr-xr-x   2 me  staff    68B 30 Oct 10:50 .
    drwxr-xr-x  11 me  staff   374B 30 Oct 10:50 ..

Presumably something is caching these dependencies. Where else can I look?

**Comment by Fritzinger** [comment]
A second after I wrote this I remembered `rake tmp:cache:clear`. Fixed, sorry.

**Comment by morenoh149** [comment]
@Fritzinger you can close your issues after they're solved
