### ISSUE TITLE
Working with jasmine

### ISSUE THREAD

**Issue by rtorr** [browserify-rails/browserify-rails#12]
Has anyone been able to require() files from jasmine tests?

**Comment by ryanlntn** [comment]
@andyl Care to share your setup? I'm trying to use browserify-rails with teaspoon and it appears to be breaking sprockets directives in teaspoon.

**Comment by pjanik** [comment]
Has anyone managed to use `jasmine-gem` and `browserify-rails`?
I'm pretty surprised I can't require files from `spec/javascripts` even though I added this path to `config.browserify_rails.paths`. Switching to node version of Jasmine won't work in my case.

**Comment by cymen** [comment]
@pjanik Have you tried running the tests with `RAILS_ENV=test`?

**Comment by cymen** [comment]
The root problem is the `jasmine-gem` moves the files around which breaks relative paths. Using non-relative paths in CommonJS is an anti-pattern and is potentially buggy with this gem -- I suggest it only for tests and even then, it isn't really a good idea.

**Comment by pjanik** [comment]
@cymen, thanks, I've tried with and without `RAILS_ENV=test`.
Actually my problem seems to be even different - when I run jasmine tests, it fails because `require` function isn't recognized. When I look at the source, it seems like my spec file wasn't browserified at all. Even though I've added `config.browserify_rails.paths << /spec\/javascripts\//` to `application.rb`.

**Comment by andyl** [comment]
I've struggled with `browserify-rails` a lot - the combination of NPM and Rails feels like Frankenstein's monster.  But I need CommonJS and IMHO `browserify-rails` is still better than ripping out sprockets entirely.  By contrast, the asset pipeline in the `Phoenix` framework works beautifully - I hope that Rails can learn from it.

That said - here is the config that works for me - hopefully this will help someone else.  I'm using `rails-assets`, am able to test with `teaspoon`.

Gems:
- sprockets 3.2.0
- sprockets-rails 2.3.1 
- browserify-rails 1.0.0
- teaspoon-jasmine 2.2.0

In `config/application.rb`:
```ruby
    # configure browserify_rails to work with coffeescript
    config.browserify_rails.commandline_options = '-t coffeeify --extension=".js.coffee"'
    # configure browserify_rails to add commonJS directives in javascript specs
    config.browserify_rails.paths << /spec\/javascripts\//
    # generate source maps in dev
    config.browserify_rails.source_map_environments << 'development'
```

Note when I upgraded from sprockets 2.2.4 to 2.3.1 it broke all the `rails-assets` gems that use `@include` statements.  The hack/workaround is to use absolute paths in the asset manifests.

I found this to be a useful reference:
http://blog.arkency.com/2015/04/bring-commonjs-to-your-asset-pipeline/
