### ISSUE TITLE
bug with dependencies cache

### ISSUE THREAD

**Issue by masarakki** [browserify-rails/browserify-rails#122]
At first, BrowserfieyProcessor load a file that contains **string** of 'require'  like  `var required = true;`.
This file should not be browserified, but `BrowserfiyProcessor#commonjs_module?` think it is a browserifyable file, and check dependencies.
Off cause, it is not browserifiable file, so `browserify --list` return no lines and **cached** to `@dependencies` .

Then, Processor load other file that really browserifiyable like `var $ = require("jquery");`,
however, `@dependencies` is already cached with `[]`, so `BrowserifyProcessor#commonjs_module?` always returns `false`.

**Comment by masarakki** [comment]
after 2.0.x, `BrowserifyProcessor` is changed to Singleton, so this problem occurs.

**Comment by mizchi** [comment]
I encoutered too

**Comment by cymen** [comment]
2.0.3 has been released with improvements to the CommonJS detection part so that `var required = true;` will no longer mark the file as being CommonJS. Do you still see the issue with it?
