### ISSUE TITLE
How to set Node Env?

### ISSUE THREAD

**Issue by Justin-lu** [browserify-rails/browserify-rails#126]
I follow the `README` config and set the `config.browserify_rails.node_env` as 'production'.
But I can't get the env by `process.env.NODE_ENV`? What should I do ?

**Comment by cymen** [comment]
Have you tried `NODE_ENV=production bundle exec rails server` or before you start rails, do a `export NODE_ENV=production` or however you would set the environmental variable on your platform? Either of those should work on an OS X or Linux computer.

**Comment by Justin-lu** [comment]
@cymen Both of them don't work for me.

**Comment by Justin-lu** [comment]
Add `envify` to package and config with 

```
    config.browserify_rails.commandline_options = '-t babelify -t envify'
```
it work for me.

**Comment by chinshr** [comment]
This is not working for me, how would I add it to this?

```
    config.browserify_rails.commandline_options = [
      "-t [babelify --presets [ es2015 react stage-0 ] --plugins [ syntax-async-functions transform-regenerator transform-decorators-legacy ] ] --extension=.jsx --extension=.js"
    ]

```
