### ISSUE TITLE
Source maps in production

### ISSUE THREAD

**Issue by dbackeus** [browserify-rails/browserify-rails#138]
Tried adding `production` to `source_map_environments` as such:
`config.browserify_rails.source_map_environments += %w[development production]`

I'm not seeing any sourcemaps after deploying to heroku though.

Also I noticed that in development the source maps are embedded into the js files themselves rather than split into separate files which wouldn't be suitable for production due to load time issues.

Is there any support for having usable source maps for production environments?

I'll add my `commandline_options` as well if that's affecting anything:
```
config.browserify_rails.commandline_options =
  %(-t coffee-reactify -t pkgify --extension=".coffee" --extension=".cjsx")
```

**Comment by cymen** [comment]
Some support was added for Exorcist with this PR:

https://github.com/browserify-rails/browserify-rails/pull/80

I don't use it so I don't know if it works or not but you could look into that. One of the limitations of the asset pipeline is that we are dealing with piped input and output -- we don't read/write files directly so to speak. So splitting into separate files is a separate concern that can't be handled well by us as far as I know -- maybe there is a way but someone would need to take on doing that.

But Exorcist might do exactly what you want:

https://www.npmjs.com/package/exorcist

**Comment by dbackeus** [comment]
Appreciate the feedback, thanks!

**Comment by cymen** [comment]
Closing assumed resolved. PR for documentation if you were able to achieve what you desired is more than welcomed!
