### ISSUE TITLE
How are package upgrades handled?

### ISSUE THREAD

**Issue by rymohr** [browserify-rails/browserify-rails#14]
If I upgrade a package (ie update version in package.json and run npm install), will all the files that require it get recompiled automatically?

Just tried using `npm link` to simulate this and it doesn't look like dependencies get recompiled.

**Comment by itsthatguy** [comment]
@rymohr, let me know if #34 resolves your issue!

**Comment by rymohr** [comment]
@itsthatguy looks good!  Thanks for the fix!
