### ISSUE TITLE
[Not an issue] Question about cache busting

### ISSUE THREAD

**Issue by franleplant** [browserify-rails/browserify-rails#141]
Hi!
    SProckets creates MD5 hashes for each file / bundle and adds them to the file name so:
`fileA.js` becomes `fileA[md5 hash].js`. I know that browserify enables this feature via plugins but how can I tell the Rail's app about that dynamic name of the file?

Thanks!
Fran

**Comment by cymen** [comment]
Do you mean when you do production builds? If so, browserify-rails just hooks into the asset pipeline and the input from Sprockets comes in via a pipe (stdin) and it emits the browserified code via a pipe (stdout) back to Sprockets/assets pipeline.

So the concern about hashing is all handled outside of the scope of browserify-rails by the asset pipeline.

**Comment by cymen** [comment]
So to finish that thought, it works however the Rails asset pipeline works. There is some caching inside of browserify-rails to try to speed up the builds but that is just used during development. So that aspect is unrelated to cache busting for production use.

**Comment by cymen** [comment]
Oh, and to see this in action, run this on your local:

`bundle exec rake assets:precompile RAILS_ENV=production`

That is how assets are typically built for production. Then look at the output in `public/assets`. More here:

http://guides.rubyonrails.org/asset_pipeline.html

**Comment by franleplant** [comment]
Great answer, thanks a lot for your time. I love the way this gem hooks into the asset pipeline, it seems to have made all the right choices. Thanks!
