### ISSUE TITLE
Files with ES6 `import` are skipped

### ISSUE THREAD

**Issue by fenec** [browserify-rails/browserify-rails#142]
`def commonjs_module?` doesn't check file for the inclusion of `import` keyword, thus files with only imports will be skipped by browserify.

probably an additional check should be added:
`|| data.to_s.include?("import")`

https://github.com/browserify-rails/browserify-rails/blob/5820330648fca48cd348641432599ce1f80e905f/lib/browserify-rails/browserify_processor.rb#L114

**Comment by cymen** [comment]
Yes, the ES6 support story hasn't been as nice as it should be. The risk here is we don't fully parse the JavaScript into an AST or some other structure that would ignore comments and ensure we are correctly targeting a global `import` call over a call to a local function that happens to be named `import` or a comment that contains the word `import`.

So it's a trade off -- some people wanted ES6 and started using it. You can solve this problem by making sure the first file that would be browserified uses require and after that, as long as it is in files pulled in by browserify, it will be browserified correctly even if it uses import.

That behavior is not obvious and as we are at 3.0.0, let's try changing the default behavior and see if it causes problems. I'll do a PR for it shortly.

**Comment by cymen** [comment]
Oh, and the reason we don't do the full parse is that it is expensive in terms of CPU-time. At least, I suspect it is. I'd be happy to be proven wrong.

**Comment by cymen** [comment]
Er, I have to push this to one of my evenings. But PRs are welcome (just need a test too).

**Comment by cymen** [comment]
@fenec I've added support for this with 3.0.1. Would you please test it and verify it works for you?

**Comment by fenec** [comment]
@cymen yes, it works correctly now. thanks!

**Comment by cymen** [comment]
@fenec Great! I'll close this issue.
