### ISSUE TITLE
ActionView::Template::Error (undefined method `gsub' for #<Array:0x007ff09940a6f0>)

### ISSUE THREAD

**Issue by sasikumar87** [browserify-rails/browserify-rails#144]
I have created a new rails 4.2.5.2 project and used 4.0.0.beta2 of `sprockets` gem, and the latest version of `browserify-rails` gem and tried the following example.

``` javascript
// foo.js
module.exports = function (n) { return n * 11 }

// application.js
var foo = require('./foo');
console.log(foo(12));
```

Now when I refresh the page, I see the following error

```
ActionView::Template::Error (undefined method `gsub' for #<Array:0x007ff09940a6f0>):
     5:     <%= csrf_meta_tags %>
     6:     <%= action_cable_meta_tag %>
     7:
     8:     <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
     9:     <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
    10:   </head>
    11:

app/assets/config/manifest.js:2
```

But it works well in sprockets 3.

**Comment by cymen** [comment]
Does Rails 4.2.5.2 really use Sprockets 4 by default? We just got compatibility with Sprockets 3. So while 4 is interesting, it is going to take some time. PRs are more than welcomed though if you want to dive into it!

**Comment by cymen** [comment]
I forgot to say, I might have some time in a couple of weeks. I'm catching up on a bunch of React/redux things I missed recently and am focused on that.

Thank you for reporting the breakage with Sprockets 4.

**Comment by alejandroiglesias** [comment]
I'm also having this issue when I do `require` a module. I'm using Sprockets 4.

**Comment by cymen** [comment]
@alejandroiglesias Would you be able to try https://github.com/browserify-rails/browserify-rails/pull/158? If not, if merged, would you be willing to report back your experience with it? I've not had time to try it in depth but apparently that PR will resolve this issue.

**Comment by cymen** [comment]
@alejandroiglesias I released 3.2.0 with the sprockets fix. Can you confirm this resolves the issue for you?

@sasikumar87 If you are still interested, can you do the same?

Thank you!

**Comment by alejandroiglesias** [comment]
@cymen sorry, I'm not working on the project using browserify-rails anymore. I can tell you that we moved on to using Webpack, so the imports were handled by it.

**Comment by cymen** [comment]
@alejandroiglesias No worries -- thanks for the reply. That is great you're using webpack directly.

I'm going to close this as fairly certain resolved. If anyone stops by and is running current browserify-rails and has this issue, please reopen and comment.
