### ISSUE TITLE
Cannot find module error, due to missing semicolon

### ISSUE THREAD

**Issue by rymohr** [browserify-rails/browserify-rails#15]
Took me a while to track this one down and still don't have a great grasp on it.  

I was getting the error `Uncaught Error: Cannot find module 'function () {}'` and after digging around noticed it looked like there were two functions calls stacked back to back.  Throwing a trailing semicolon onto the end of the browserify output fixed things:

```
def browserify
  run_browserify(options) + ";"
end
```

I'll try to reduce it to a test case but wanted to throw this out there in case anyone else is running into the same issue. These are coffeescript files so I'm not sure if it's a browserify or coffeeify issue.

**Comment by nornagon** [comment]
I'm seeing this with browserify 6.3.0, browserify-incremental 1.4.0 and browserify-rails 0.7.2. Adding ';' to the return value of `run_browserify` fixes the issue (after clearing out the `tmp/` directory).
