### ISSUE TITLE
Alternative tooling using Webpack, via the gem react_on_rails

### ISSUE THREAD

**Issue by justin808** [browserify-rails/browserify-rails#152]
Would the maintainers be OK with a PR to add to the README.md a note on using webpack with Rails, via the [gem react_on_rails](https://rubygems.org/gems/react_on_rails), as an alternative to using browserify-rails? I'd be happy to list browserify-rails with react as an alternative to using react_on_rails on our README.md.

https://github.com/shakacode/react_on_rails/ is a system for using webpack to integrate React with Rails. While the gem is mostly specific to using React on Rails views, it has some features that would be of interest to users outside of React. For example, the integration with webpack ensures that "bundles" (compiled JavaScript put into the asset pipeline) is current before tests start.

https://github.com/shakacode/react-webpack-rails-tutorial is a live example of using this technique.

Thanks for your consideration.

**Comment by cymen** [comment]
I'm happy to merge a PR that mentions alternatives. I personally am of the opinion that being in the asset pipeline has more cons than pros so I view this gem as a way to get to CommonJS and then jump off the asset pipeline. But other people view it differently (which is completely fine of course) and listing options is always good in my opinion.

So yes, such a PR would be welcomed.

**Comment by justin808** [comment]
@cymen Thanks! See https://github.com/browserify-rails/browserify-rails/pull/153

**Comment by cymen** [comment]
Merged PR.
