### ISSUE TITLE
Window is not defined while parsing file

### ISSUE THREAD

**Issue by BrunoQuaresma** [browserify-rails/browserify-rails#159]
When i access:

Error while running `/var/www/eventgram/node_modules/.bin/browserifyinc -t [ babelify --presets [ es2015 ] --extensions .es6 ] --list --cachefile=/var/www/eventgram/tmp/cache/browserify-rails/browserifyinc-cache.json -o "/var/www/eventgram/tmp/cache/browserify-rails/output20160410-5237-5ytx1u" -`:

events.js:141
      throw er; // Unhandled 'error' event
      ^

ReferenceError: window is not defined while parsing file: /var/www/eventgram/app/assets/javascripts/services/instagram.es6

Someone get this error?

**Comment by criticerz** [comment]
@BrunoQuaresma were you able to figure this out? I'm getting the same error

**Comment by mafigit** [comment]
@BrunoQuaresma Having the same error...

**Comment by BrunoQuaresma** [comment]
I asked that question some time ago. Apparently it was ignored. I look forward to other alternatives such as using the webpack in a separate client app.

**Comment by cymen** [comment]
This kind of issue is completely outside the realm of browserify-rails which is probably why nobody stepped up to try to answer it here. So you'd want to go upstream to browserify itself or more likely to where the error is coming from (and find the issue there). If your `instagram.es6` file uses window, you would need to tell browserify it's okay to have window as a global. You would have the same need in webpack.

**Comment by BrunoQuaresma** [comment]
Exactly @cymen. This is a problem found in server render applications that use window object without verification before.
