### ISSUE TITLE
Recompiling every request with upgrade to sprockets 3.6.0

### ISSUE THREAD

**Issue by mockdeep** [browserify-rails/browserify-rails#160]
We updated sprockets to 3.6.0 today from 3.5.2 and afterwards every single request causes browserify to run again, even if it's simply refreshing the same page.

**Comment by cymen** [comment]
Ah! No good. Looking at the Sprockets changelog for 3.x:

https://github.com/rails/sprockets/blob/3.x/CHANGELOG.md

**3.6.0** (April 6, 2016)

* Add `Manifest#find_sources` to return the source of the compiled assets.
* Fix the list of compressable mime types.
* Improve performance of the `FileStore` cache.

That last one sounds suspicious.

**Comment by cymen** [comment]
But the merge commits for it don't look odd. Looks like we'll need to try to repro and debug.

**Comment by cymen** [comment]
@mockdeep Do you still see this with Sprockets 3.6.3?

**Comment by mockdeep** [comment]
@cymen nope, everything seems to be working nicely! I think we can close this out.

**Comment by cymen** [comment]
@mockdeep Nice, I'll close.

**Comment by mockdeep** [comment]
@cymen so I was running into this issue (or something like it) again today. It turns out I was running [`teaspoon`](https://github.com/modeset/teaspoon) while I was trying to navigate around on localhost, and every time I clicked a link I ended up with a lengthy recompiling. Not sure if it's the same as the issue I was seeing before, but killing `teaspoon` made localhost navigable. Hoping to get off `teaspoon` soon-ish, along with completing the transition to node-style requires.

**Comment by cymen** [comment]
@mockdeep Interesting! I wonder what teaspoon is doing to cause that. But that is useful and good to know.

**Comment by mockdeep** [comment]
@cymen `teaspoon` uses the asset pipeline, so it'll be running `browserify-rails` as well. It seems to clobber the cache regardless, so if I work some on localhost, then run `teaspoon`, then go back to localhost, I end up having to wait for a complete recompile again. I think they do inject some of their own dependencies, so I wonder if that invalidates the browserify cache...

**Comment by cymen** [comment]
@mockdeep It might be worth trying setting `expand_assets` to false in the teaspoon configuration. That might be extremely annoying though in actual usage when trying to figure out why something failed. But it might stop the recompile and you'd only have to pay for it when you actually need the stack trace (by toggling `expand_assets` back on). Just a guess though -- I was looking at this:

https://github.com/modeset/teaspoon/wiki/Teaspoon-Configuration

**Comment by mockdeep** [comment]
@cymen unfortunately that doesn't seem to have done the trick. It still recompiles both ways. It also causes a whole bunch of other failures for some reason.

**Comment by cymen** [comment]
@mockdeep Ah! Thanks for trying.

**Comment by mockdeep** [comment]
@cymen another thought that might be useful is if the browserify output that appears in the logs had some identifying info about what file is being processed. It could give me a better idea of what is getting recompiled every time.

**Comment by mockdeep** [comment]
Hmm, now I'm seeing the issue without teaspoon involved. Just clicking back and forth between 2 different pages on localhost it's recompiling over and over again. It seems super inconsistent, actually. I just clicked back and forth 3-4 times without any recompilation, no changes to any of the code, then one more time and it's recompiling again, again with no changes to the code. Sometimes the recompilation doesn't seem to take as long either. When they seem to have settled going to a 3rd page causes the whole thing to start again. Reverting to sprockets `3.5.2` resolves the issue.

**Comment by cymen** [comment]
In theory, it should be logging to the Rails log if the log level is set to debug. It would be nice to have an option to enable logging too. The code is in `lib/browserify-rails/browserify_logger.rb`.

**Comment by mockdeep** [comment]
It is logging, but the logs are pretty nondescript:

```
Browserify: /home/fletch/Dropbox/projects/chalk/synchroform/node_modules/.bin/browserifyinc -t reactify --extension=".js.jsx" --cachefile=/home/fletch/Dropbox/projects/chalk/synchroform/tmp/cache/browserify-rails/browserifyinc-cache.json -o "/home/fletch/Dropbox/projects/chalk/synchroform/tmp/cache/browserify-rails/output20160722-22860-rbkmh0" -
Browserify: /home/fletch/Dropbox/projects/chalk/synchroform/node_modules/.bin/browserifyinc -t reactify --extension=".js.jsx" --list --cachefile=/home/fletch/Dropbox/projects/chalk/synchroform/tmp/cache/browserify-rails/browserifyinc-cache.json -o "/home/fletch/Dropbox/projects/chalk/synchroform/tmp/cache/browserify-rails/output20160722-22860-ug5hxk" -
Browserify: /home/fletch/Dropbox/projects/chalk/synchroform/node_modules/.bin/browserifyinc -t reactify --extension=".js.jsx" --cachefile=/home/fletch/Dropbox/projects/chalk/synchroform/tmp/cache/browserify-rails/browserifyinc-cache.json -o "/home/fletch/Dropbox/projects/chalk/synchroform/tmp/cache/browserify-rails/output20160722-22860-8ccdpu" -
```

**Comment by cymen** [comment]
Have you tried doing this outside of your Dropbox folder? Or at least with Dropbox turned off completely (bit hard to do sometimes)? Just curious if maybe the Dropbox sync process(es) are potentially causing issues.

**Comment by cymen** [comment]
But yeah, it's fairly nondescript -- browserify-rails is given a input stream as opposed to a file name from the asset pipeline. There is probably some way to log the origin of the input stream but currently it isn't. It would be more helpful if it could.
