### ISSUE TITLE
Using Heroku Pipelines causes downtime

### ISSUE THREAD

**Issue by Arjeno** [browserify-rails/browserify-rails#163]
Hi guys. I'm running into problems with using Heroku Pipelines and browserify-rails. Or atleast, I think it has to do with browserify-rails. Let me explain.

Heroku Pipelines (not to be confused with the asset pipeline) is an awesome service of working in different stages of an app. You can promote apps from staging to production. This is where our app is struggling. Once I deploy to staging and then promote staging to production the production app becomes unresponsive for about 5-10 minutes. I didn't have this problem before (without browserify-rails). Also when I directly deploy to Heroku using a simple `git push` the problem doesn't occur. I think it has to do with assets precompilation. Perhaps browserify-rails thinks that some assets are missing and then precompiles them on the fly? Because I'm not 100% sure and before I completely dive into the issue, maybe people who have a bit more knowledge of browserify-rails can shed some light on this.

Thank you!

**Comment by richardvenneman** [comment]
We're running two apps on Pipelines with browserify-rails and they're booth running smooth. Assets are precompiled in staging, promoting to production with near zero downtime.

I don't have Heroku preboot enabled.
