### ISSUE TITLE
Errors on assets:precompile 'import' and 'export' may appear only with 'sourceType: module'

### ISSUE THREAD

**Issue by NickHurst** [browserify-rails/browserify-rails#168]
I'm currently trying to deploy my app, and I'm getting a BrowersifyRails error when the assets are precompiling.

Note: running `RAILS_ENV=production bundle exec rake assets:precompile` on my local machine works fine, however when pushing, this is the stack trace I receive:

```
BrowserifyRails::BrowserifyError: Error while running `/var/wwwl/releases/20160711155034/node_modules/.bin/browserify -t [ vueify --extensions .vue ] -t [ babelify --presets [ es2015 ] --extensions .js ] --list -o "/var/wwwl/releases/20160711155034/tmp/cache/browserify-rails/output20160711-29669-3lhy5p" -`:


events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Parsing file /var/www/20160711155034/app/assets/javascripts/vue/components/Notification.vue: 'import' and 'export' may appear only with 'sourceType: module' (14:0)
    at Deps.parseDeps (/var/www/20160711155034/node_modules/browserify/node_modules/module-deps/index.js:453:28)
    at fromSource (/var/www/20160711155034/node_modules/browserify/node_modules/module-deps/index.js:390:44)
    at /var/www/releases/20160711155034/node_modules/browserify/node_modules/module-deps/index.js:384:17
    at ConcatStream.<anonymous> (/var/www/releases/20160711155034/node_modules/browserify/node_modules/concat-stream/index.js:36:43)
    at ConcatStream.emit (events.js:117:20)
    at finishMaybe (/var/www/releases/20160711155034/node_modules/browserify/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:475:14)
    at Object.afterWrite (/var/wwwl/releases/20160711155034/node_modules/browserify/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:361:3)
    at Object.immediate._onImmediate (timers.js:381:16)
    at processImmediate [as _immediateCallback] (timers.js:363:15)

...

Tasks: TOP => assets:precompile
```

Application.rb:

```ruby
config.browserify_rails.paths = [/app\/assets\/javascripts\/vue/, /node_modules\//]
config.browserify_rails.commandline_options = "-t [ vueify --extensions .vue ] -t [ babelify --presets [ es2015 ] --extensions .js ]"

config.assets.initialize_on_precompile = false
```

**Comment by cymen** [comment]
Are you able to build your assets locally when in RAILS_ENV=production? I'd try this command:

`bundle exec rake assets:precompile RAILS_ENV=production`

If so, then `rm -rf node_modules` and reinstall them but with `npm install --production`. Then run the above asset compile step again. If it doesn't work this time, then look at what is in the `devDependencies` of your `package.json` that is needed to compile the code.

Is this on Heroku?

**Comment by NickHurst** [comment]
@cymen I'm able to precompile locally. This is not on heroku, on a CentOS/apache box deployed with capistrano.

Other things I've tried:

Downgrading to bablelify 6.x (causes different error, solution was to upgrade)
Set `initialize_on_precompile` to true
Commented out `js_compressor`

I have a `babelrc` which just contains:

```
{ "presets": ["es2015"] }
```

**Comment by cymen** [comment]
What about with just the production node module install?

**Comment by NickHurst** [comment]
@cymen Same result, can precompile locally, can't on staging server.

**Comment by cymen** [comment]
That sounds frustrating! I'd go through piece by piece and compare versions to try to figure out why the server is different than local. It sounds like you're already doing that.

Check out this issue:

https://github.com/vuejs/vueify/issues/108

It may be a babel thing -- if you have a node module in your gobal modules locally, it might get resolved locally while on the server it does not.

**Comment by NickHurst** [comment]
I was able to fix it by installing these node modules and adding them as dependencies:

"babel-core"
"babel-runtime"
and
"vue-hot-reload-api"

Previously my dependencies just looked like:
"babel-plugin-transform-runtime": "^6.9.0",
"babel-polyfill": "^6.9.1",
"babel-preset-es2015": "^6.9.0",
"babelify": "7.2.0",
"browserify": "^13.0.1",
"browserify-incremental": "^3.1.1",
"vue": "^1.0.25",
"vue-resource": "^0.9.0",
"vueify": "^8.6.0",
"vuex": "^0.8.0"
