### ISSUE TITLE
Browserify use with Sprocket cannot find module on an existed path?

### ISSUE THREAD

**Issue by hieuhlc** [browserify-rails/browserify-rails#170]
This is the raised exception said that Browserify cannot find module `moment` on `javascripts/common`

<img width="989" alt="screen shot 2016-07-24 at 21 16 15" src="https://cloud.githubusercontent.com/assets/4828178/17084322/f3fbcdb0-51e4-11e6-909b-28140b01e4d3.png">

But it was there, and this code works fine before when using only Sprocket.

<img width="639" alt="screen shot 2016-07-24 at 21 16 58" src="https://cloud.githubusercontent.com/assets/4828178/17084327/06adfa00-51e5-11e6-9ece-aae57f0f6ce4.png">

I think i missed some configuration. Please help me.

**Comment by cymen** [comment]
Browserify is expecting to use moment as a module (ie put moment in package.json and `npm install` so it shows up in `node_modules/moment`) -- if you want to use moment as pulled in from Sprockets, you need to configure Browserify to tell it moment is a global.

**Comment by hieuhlc** [comment]
@cymen here is my `package.json`

```json
{
  "name": "test",
  "dependencies": {
    "browserify": "~10.2.4",
    "browserify-incremental": "^3.0.1",
    "react-dragula": "^1.1.16"
  },
  "license": "MIT",
  "engines": {
    "node": ">= 0.10"
  }
}
```

I supposed moment is used by a dependency. But I can't find how to configure Browserify to use moment as global. Read across your docs :/

**Comment by cymen** [comment]
@hieuhlc That wouldn't be in the docs here -- it would be in the docs for browserify. You could try browserify-shim as outlined here:

http://stackoverflow.com/questions/23125338/how-do-i-use-browserify-with-external-dependencies

Just replace `jQuery` with `moment` of course.

**Comment by hieuhlc** [comment]
@cymen I did use `browserify-shim` but got no luck. I had to move folder `common` to `vendor/assets/javascripts` to avoid Sprocket processing `.js` files. That worked.
Now I used browserify normally 💯 
Thank you very much for your kind support 😄
