### ISSUE TITLE
Browserify syntax error on CI (Circle CI)

### ISSUE THREAD

**Issue by cjmarkham** [browserify-rails/browserify-rails#171]
When running RSPEC tests on Circle CI I get the following error:

```
# BrowserifyRails::BrowserifyError: # Error while running `/home/ubuntu/web/node_modules/.bin/browserifyinc -t [ babelify --presets [ es2015 ] --extensions .js ] --list --cachefile=/home/ubuntu/web/tmp/cache/browserify-rails/browserifyinc-cache.json -o "/home/ubuntu/web/tmp/cache/browserify-rails/output20160726-15146-6fj4i" -`:
```

This comes from a supposed syntax error in one of my react components

```
return {...state}
```

This doesn't happen locally, only on the CI.

`npm test` works fine, just the Rspec tests that fail

Package.json

```
"dependencies": {
  "react": "^15.2.1",
  "react-dom": "^15.2.1",
  "react-redux": "^4.4.5",
  "redux": "^3.5.2",
  "babel-preset-es2015": "^6.1.2",
  "babel-preset-react": "^6.1.2",
  "babelify": "^7.2.0",
  "browserify": "^12.0.1",
  "browserify-incremental": "^3.0.1"
},
"devDependencies": {
  "enzyme": "^2.4.1",
  "grunt": "^0.4.5",
  "grunt-contrib-jshint": "~0.10.0",
  "mocha": "^2.5.3",
  "chai": "^3.5.0",
  "react-addons-test-utils": "^15.0.2",
  "sinon": "^1.17.3"
}
```

**Comment by cymen** [comment]
Do you have `transform-object-rest-spread` as a plugin for babel (and if so, need to add as dev dependency)? I think the spread operator got pulled back to a plugin.

**Comment by cymen** [comment]
Actually, looks like `babel-preset-es2015` includes `babel-plugin-transform-es2015-spread`. What is your babel configuration?

**Comment by cjmarkham** [comment]
I tried adding `transform-es2015-spread` to my `.babelrc` and to the command line options 
```
config.browserify_rails.commandline_options = "-t [ babelify --presets [ es2015 react ] --plugins [ transform-es2015-spread ] ]"
```

But I was facing the same issue. I have added the `babel-plugin-transform-object-rest-spread` plugin and used it in `.babelrc` and the command line options and it appears to work now. Thanks

Final code:

```
config.browserify_rails.commandline_options = "-t [ babelify --presets [ es2015 react ] --plugins [ transform-object-rest-spread ] ]"
```

.babelrc
```
{
    "presets": ["es2015", "react"],
    "plugins": ["transform-object-rest-spread"]
}
```

package.json

`"babel-plugin-transform-object-rest-spread": "^6.1.2",`
