### ISSUE TITLE
How to except files / folder from browserify?

### ISSUE THREAD

**Issue by hieuhlc** [browserify-rails/browserify-rails#172]
I want to exclude specified file / folder from browserify process, allow only Sprocket process it, how can i do it?
Thanks in advance.

**Comment by gauravtiwari** [comment]
@hieuhlc You could only process certain file extensions with browserify, for example: `.es6.js` or `.jsx` by specifying extension option in browserify. 

```ruby
config.browserify_rails.commandline_options = "-t babelify --extension=\"es6.js\""
```

You can checkout this repo for reference: https://github.com/gauravtiwari/browserify_on_rails/tree/master/app/assets/javascripts

**Comment by hieuhlc** [comment]
Yes i used that solution. It would be nice if there is a config for this.

**Comment by gauravtiwari** [comment]
We have added the example repo in the readme.
