### ISSUE TITLE
Use multiple transform in commandline_options

### ISSUE THREAD

**Issue by hieuhlc** [browserify-rails/browserify-rails#174]
I want to use `envify` to set node environment along with `babelify` react-es6 transform but this config is not working:

```ruby
config.browserify_rails.commandline_options = "-t envify --NODE_ENV development [ babelify --presets [ react es2015 stage-0 ] --extensions .jsx ]"
```

Please help me.

**Comment by gauravtiwari** [comment]
You don't need `envify`. You could do this. 
```
config.browserify_rails.commandline_options = "NODE_ENV=development node_modules/browserify/bin/cmd.js  node_modules/babelify/index.js --presets [ react es2015 stage-0 ] --extension=\".jsx\""
```

**Comment by hieuhlc** [comment]
@gauravtiwari it's not working. See #126

**Comment by gauravtiwari** [comment]
@hieuhlc Did you do `export NODE_ENV=production` environment variable in terminal?

**Comment by hieuhlc** [comment]
@gauravtiwari It actually works! I figured it out that was browserify incremental cache. I was almost pulling my hair out 😄 

Here is my code in `config/development.rb`

```ruby
config.browserify_rails.node_env = "development"
```

In `package.json`

```javascript
"browserify": {
  "transform": [
    [ "babelify", { "presets": [ "react", "es2015", "stage-0" ], "extensions": ".jsx" } ],
    [ "envify" ]
  ]
}
```

**Comment by gauravtiwari** [comment]
Awesome 👍
