### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by dspoonia7** [browserify-rails/browserify-rails#175]
I am getting `Uncaught RangeError: Maximum call stack size exceeded` error (and entire page is rendering totaly blank). After adding [React Developer Tools](https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi?hl=en) extension in my browser, everything works normal but on removing/disabling this extension, I am getting that error.

I have setup rails-react-browserify. I raised this issue [here](https://github.com/reactjs/react-rails/issues/589) also.

**Comment by dspoonia7** [comment]
https://github.com/reactjs/react-rails/issues/589

**Comment by soykje** [comment]
Hello,

I'm having the same kind of issues, did you find any solution? Thx in advance

**Comment by dspoonia7** [comment]
Hey thats because some plugin ([raven-js](https://github.com/getsentry/raven-js), was added earlier in vendor) was causing some version mismatch.
