### ISSUE TITLE
FATAL ERROR: JS Allocation failed - process out of memory

### ISSUE THREAD

**Issue by joncursi** [browserify-rails/browserify-rails#177]
While deploying to our staging environment, we are hitting the following error while rails is precompiling assets:

```
BrowserifyRails::BrowserifyError: Error while running `/apps/appName/releases/20161005200217/node_modules/.bin/browserifyinc -t [ babelify --presets [ es2015 react stage-0 ] --plugins [ transform-class-properties ] ] --list --cachefile=/apps/appName/releases/20161005200217/tmp/cache/browserify-rails/browserifyinc-cache.json -o "/apps/appName/releases/20161005200217/tmp/cache/browserify-rails/output20161005-18666-t1gl16" -`:

FATAL ERROR: JS Allocation failed - process out of memory
```

We have 630 npm packages under the node_modules directory, most of which are indirect dependencies of the packages we use.

We have increased our server's ram to 16GB so we have eliminated hardware / RAM from being a possible source of the problem. Can you please provide some insight into why this step would be failing?

**Comment by cymen** [comment]
What version of node and npm are you using? If npm < 3, I wonder if upgrading to more recent version with the flattening of node_modules would help.

It might be worth taking a look at this StackOverflow thread too:

http://stackoverflow.com/questions/13616770/node-js-fatal-error-js-allocation-failed-process-out-of-memory-possible

In case anything there applies.

**Comment by joncursi** [comment]
@cymen thanks for your reply. I've narrowed this down a little bit. We upgraded node and npm to more recent versions (node 6.2.2 and npm 3.9.5), but we're still hung up on browserify-rails. Here's an example of the command we're running as part of our deploy process:

```
/apps/appName/releases/20161005222807/node_modules/.bin/browserifyinc -t [ babelify --presets [ es2015 react stage-0 ] --plugins [ transform-class-properties ] ] --list --cachefile=/apps/appName/releases/20161005222807/tmp/cache/browserify-rails/browserifyinc-cache.json -o "/apps/appName/releases/20161005222807/tmp/cache/browserify-rails/output20161005-14432-cjvvuj" -
```

The error we're getting now is:

```
/apps/appName/releases/20161005222807/node_modules/browserify-cache-api/lib/BrowserifyCache.js:191
  fs.writeFile(cacheFile, JSON.stringify(cache), {encoding: 'utf8'}, function(err) {
                               ^

RangeError: Invalid string length
    at Object.stringify (native)
    at storeCache (/apps/appName/releases/20161005222807/node_modules/browserify-cache-api/lib/BrowserifyCache.js:191:32)
    at Browserify.<anonymous> (/apps/appName/releases/20161005222807/node_modules/browserify-cache-api/lib/BrowserifyCache.js:182:7)
    at Browserify.g (events.js:291:16)
    at emitNone (events.js:86:13)
    at Browserify.emit (events.js:185:7)
    at removeCacheBlocker (/apps/appName/releases/20161005222807/node_modules/browserify-cache-api/lib/BrowserifyCache.js:69:7)
    at /apps/appName/releases/20161005222807/node_modules/browserify-cache-api/lib/BrowserifyCache.js:119:9
    at /apps/appName/releases/20161005222807/node_modules/browserify-cache-api/lib/BrowserifyCache.js:218:5
    at FSReqWrap.oncomplete (fs.js:123:15)
```

From what I see here: https://github.com/nodejs/node-v0.x-archive/issues/14170 - this is actually a JS memory allocation issue but node / v8 is unable to report it correctly. Now, when I inspect the `cachefile` being passed in to browserify, I find that it's a 6MB JSON file and from the looks of it, browserify is trying to parse it (and running out of memory).

Any guidance you can provide on how to mitigate that?

**Comment by joncursi** [comment]
Update: it appears that the cachefile may indeed have been corrupt in some way, or just too damn big to process in JS. We're using Capistrano to deploy to our servers, and it's storing the tmp/cache/browserify-rails/browserifyinc-cache.json in a symlinked, shared directory so all releases can pull the same file. I temporarily changed the filename so that browserify would generate a new cachefile on the next deploy, and you can see the massive size difference between the old cachefile and the one that was newly generated:

![screen shot 2016-10-05 at 7 13 40 pm](https://cloud.githubusercontent.com/assets/4974609/19135062/07959e30-8b30-11e6-8145-913f160b9008.png)

So I guess my question is now, how does the cachefile get into this unprocessable state? We'd like to prevent it in the future. Thanks!

**Comment by cymen** [comment]
Ouch. This is where... It gets a bit complicated. We are using browserify-inc to speed up compilation. It helps even for a single pass however it might be worth disabling the cache on your production builds and see if it is a better experience.

You can disable the cache with:

```ruby
config.browserify_rails.use_browserifyinc = false
```

In your production configuration.

**Comment by cymen** [comment]
It might be worth opening an issue over https://github.com/jsdf/browserify-incremental too if disabling it for production builds isn't a viable option.

**Comment by joncursi** [comment]
We're happy to disable the cache on our server environments. Our deploys take a bit longer without the caching, but we'll take that any day over potential instability. Thank you for your help, @cymen!
