### ISSUE TITLE
Working with aliasify

### ISSUE THREAD

**Issue by maxhungry** [browserify-rails/browserify-rails#178]
With aliasify you can do this:
```
// package.json
  "aliasify": {
    "aliases": {
      "underscore": "lodash"
    }
  }
```

Is `browserify-rails` currently support this as command line options?

**Comment by maxhungry** [comment]
aliasify actually works out of the box.

**Comment by chrise86** [comment]
@maxhungry did you just use it in the `package.json` file or did you add it to the `application.rb` options?

**Comment by maxhungry** [comment]
I end up putting config in `package.json`, as I can't figure out a way to do command line options in `application.rb`.

**Comment by chrise86** [comment]
Hmm ok. I'm trying to use Preact in place of React, but still using the `react-rails` gem to use the `react_component` helper and server rendering - it's not going very well... 😔
