### ISSUE TITLE
browserify.transform in package.json is being ignored

### ISSUE THREAD

**Issue by paulozoom** [browserify-rails/browserify-rails#185]
When configuring browserify transforms through package.json, they’re not being applied. However, if specified through `Rails.application.config.browserify_rails.commandline_options`, they are.

Example config:

```json
  "browserify": {
    "transform": [
      "browserify-shim",
      ["babelify", {
        "presets": ["es2015", "react", "stage-0"],
        "plugins": ["lodash"]
      }]
    ]
  },
```

**Comment by AshlessCinder** [comment]
this is from the readme:

> ## Using Browserify Transforms
> 
> You can easily use a browserify transform by adding it to your `package.json`, then adding the transform flag to your `application.rb`, using `config.browserify_rails.commandline_options`. For example, here is how you can add ES6 support in your app:
> 
> 1. Add `babelify` and `babel-preset-es2015` to your `package.json` in your app's root directory, then run `npm install`
> 2. Add this line to your config/application.rb:
>    `config.browserify_rails.commandline_options = "-t [ babelify --presets [ es2015 ] --extensions .es6 ]"`
> 3. Create some `.es6` files and require them with `var m = require('./m.es6')` or `import m from './m.es6'`
> 4. Restart your server, and you now have ES6 support!

so you need to do both by design I guess
