### ISSUE TITLE
Cannot find module '../' when using require()

### ISSUE THREAD

**Issue by aurels** [browserify-rails/browserify-rails#190]
Hi,

I'm successfully using `browserify-rails` with es6 and React in several Rails apps. But I cannot make it work with this one I'm currently migrating. I've been fighting for hours not finding any explanation.

Here are all the relevant files of the project : 
https://gist.github.com/aurels/f957fcc323169d2ba0a160975a97747a

As soon as I insert a `require()`, it breaks with this error : 

    BrowserifyRails::BrowserifyError in Invoices#index
    Showing myapp/app/views/layouts/application.html.erb where line #15 raised:
    
    Error while running `myapp/node_modules/.bin/browserifyinc -t [ babelify --presets [ es2015 react ] --extensions .es6 ] --list --cachefile=myapp/tmp/cache/browserify-rails/browserifyinc-cache.json -o "myapp/tmp/cache/browserify-rails/output20170211-7503-1k1shi7" -`:
    
    module.js:457
        throw err;
        ^
    
    Error: Cannot find module '../'
        at Function.Module._resolveFilename (module.js:455:15)
        at Function.Module._load (module.js:403:25)
        at Module.require (module.js:483:17)
        at require (internal/module.js:20:19)
        at Object.<anonymous> (/Users/aurels/Dropbox/Dev/invoicer/node_modules/.bin/browserifyinc:3:29)
        at Module._compile (module.js:556:32)
        at Object.Module._extensions..js (module.js:565:10)
        at Module.load (module.js:473:32)
        at tryModuleLoad (module.js:432:12)
        at Function.Module._load (module.js:424:3)

I removed all JS/ES6 files other then `application.js` to have the smallest tree possible.

Am I missing something ? Do you need more infos ? Thanks.

Aurels

**Comment by cymen** [comment]
Is it possible to get a repo up that demonstrates the issue? I realize you might have code you don't want to share but it is hard to debug otherwise. You might try forking your repo, redacting the code you don't want to share until there is a working demo of the failure without any private code.

**Comment by aurels** [comment]
Yes I've planed to do that ;-) Thanks.

**Comment by aurels** [comment]
So. I don't know what I've done but it now works and if I add everything back to the project too. I guess it was a cache error... 

I had nonetheless done this a million time (at least) : `rake tmp:clear`.

My other hypothesis is that I disabled "incremental" and enabled it again. But I'm not sure.

Anyway, I'll close this and reopen if I encounter it again ;-)

**Comment by vpaul08** [comment]
I tried what you did but I'm also struggling with this. All I'm trying to do is to use react-rails and browserify-rails together. I'm also including material-ui to be used with react but as soon as I use require anywhere in my code, I run into this error.

Tried running tmp:clear, asset:clean, etc but no success. 

Any suggestion will be appreciated.
