### ISSUE TITLE
Require throwing error in rails

### ISSUE THREAD

**Issue by dmc2015** [browserify-rails/browserify-rails#199]
I have gone through the install instructions for this.

I keep getting this error now and I have tried deleting the tmp/cache folder. (based on this video https://www.youtube.com/watch?v=D4y7WnLMy18)

The error I am getting from rails is:

BrowserifyRails::BrowserifyError at /account2_systems_access/1
Error while running `/**/**/**/**/**/node_modules/.bin/browserifyinc --list --cachefile=/**/**/**/**/**/tmp/cache/browserify-rails/browserifyinc-cache.json -o "/**/**/**/**/**/tmp/cache/browserify-rails/output20170502-29873-a6d5q9" -`:

events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: Cannot find module './options' from '/**/**/**/**/**/app/assets/javascripts'
    at /**/**/**/**/**/node_modules/browser-resolve/node_modules/resolve/lib/async.js:55:21
    at load (/**/**/**/**/**/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/**/**/**/**/**/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /**/**/**/**/**/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:114:15)

  (in /**/**/**/**/**/app/assets/javascripts/**.js)

^^ the last file is the file that I was requiring another file in.

If I comment out that require line I no longer get this error.

**Comment by cymen** [comment]
I'm going to close this issue as it appears to be stale. If you still need help, please reopen.
