### ISSUE TITLE
Browserify breaks action cable

### ISSUE THREAD

**Issue by bajalovic** [browserify-rails/browserify-rails#204]
I am experiencing some unusual issue. When I start rails server (puma) and open localhost, actioncable is working correctly. Then, I change some JS and reload page in browser, then action is called, and browserify executed

```
Browserify: /path-to-project/node_modules/.bin/browserifyinc -t [ babelify --presets [ es2015 ] ] --list --cachefile=/path-to-project/tmp/cache/browserify-rails/browserifyinc-cache.json -o "/path-to-project/tmp/cache/browserify-rails/output20170612-42190-g6ql2m" -
Browserify: /path-to-project/node_modules/.bin/browserifyinc -t [ babelify --presets [ es2015 ] ] --cachefile=/path-to-project/tmp/cache/browserify-rails/browserifyinc-cache.json -o "/path-to-project/tmp/cache/browserify-rails/output20170612-42190-16qdbtu" -
```

After this, action cable stops working, and in network inspection window (Chrome) I see multiple `/cable` requests. It connects, get `Opcode (-1)` error, and re-try, and so on.. When I restart server, everything works fine, until next JS change...

I tried this on  Rails 5.0.3, Ruby 2.2.2p95, Puma server 3.9.1, ActionCable is also 5.0.3. and also on 
Rails 5.0.0.1, Ruby 2.2.2p95, Puma server 3.6.2, and ActionCable 5.0.0.1.

**Comment by cymen** [comment]
@bajalovic That sounds like a hot reload issue although you say you reload the page so it seems not? Odd. Maybe worth looking at this to see if any ideas there:

https://github.com/wclittle/Rails5-ActionCable-Redux-React-ChatAppExample

Also, if this is not a legacy project, you might consider trying [rails/webpacker](https://github.com/rails/webpacker) or a more modern approach than this gem. Another issue brought up this topic and I updated the README to share some opinionated thoughts on this topic here: 

https://github.com/browserify-rails/browserify-rails#should-you-use-this-gem

**Comment by bajalovic** [comment]
hi @cymen I already had on my roadmap to migrate to webpacker, and this issue just fast-forwarded that task to the top :)

I am not sure what the problem was, maybe my project became too big (i have like ~100 JS files which I do not think is too much)?!  

I will close this for now as I am not using browserify anymore.

**Comment by cymen** [comment]
Yeah, 100 files should be fine. When I've had performance problems in the past, it was more just slow -- it always worked (besides when browserify-incremental got buggy and required a clear of the cache). So it is probably something else.

But :+1: on migrating to webpacker.
