### ISSUE TITLE
Production env. randomly not compiling certain .js files

### ISSUE THREAD

**Issue by gotoAndBliss** [browserify-rails/browserify-rails#205]
My local and beta work fine. But on prod., a core file was getting skipped because of this line :

```
var { configureStore } = require('./configureStore');
```

Removing this line, and then `browserify-rails` would correctly parse the file in its entireity. Add it back, and the file would be skipped.

There is absolutely nothing different between my beta and production. They share all systems identically and were built as an additional safeguard before deploying to production. However, once I deploy to prod. the file gets skipped.

After hours of deliberation, reading through all the open and closed issues in this git, skimming through the source code, I added just a just a couple more tweaks to my application.rb file

```
config.browserify_rails.use_browserifyinc = true
    config.browserify_rails.commandline_options = ["-t [ babelify --presets [ es2015 react stage-0 ] --plugins [ syntax-async-functions transform-regenerator ] ]", "-t coffeeify --extension=\".js.coffee\""]
```

And redeployed to production. This time, my file went through! But a second file would not parse because of a very similar issue. It has this in the code :

```
let { search } = require('../../actions/search');
```

Removing this line, and the file magically appears. Add it back, and the file disappears.

Any ideas why this might be happening?

**Comment by stevensona** [comment]
Sounds like something similar to what I experienced.. #201 Was using an old version of sprockets and browserify-rails inadvertently

**Comment by cymen** [comment]
Closing -- please reopen if you wish to continue discussing this issue.
