### ISSUE TITLE
Problem when try require module in my html.erb file into script tags

### ISSUE THREAD

**Issue by dersar00** [browserify-rails/browserify-rails#213]
When i try to require something i got a exception “Uncaught ReferenceError: require is not defined”.
i need it for uppy-server
my html.erb file:
https://pastebin.com/DAP47YtF

**Comment by cymen** [comment]
browserify-rails only processes JavaScript files so I think this problem is elsewhere. Is the exception at run time in the browser? Does that pastebin reflect the actual contents or do you have the `require` in the pastebin example uncommented when you get the exception?

**Comment by dersar00** [comment]
I have a problem, when the line is uncomment. The exception in browser at run time.

**Comment by cymen** [comment]
So if you wanted to use require in the browser, you would need support for it there. This might be useful:

https://stackoverflow.com/questions/6971583/node-style-require-for-in-browser-javascript

**Comment by cymen** [comment]
I forgot to say, this is not a problem browserify-rails fixes. It does not process .erb files -- only .js files.
