### ISSUE TITLE
ES6 code with no imports

### ISSUE THREAD

**Issue by pioz** [browserify-rails/browserify-rails#214]
In my application.js i've this include: `//= require ready`
and the `app/assets/javascripts/ready.js` is this:

```
const ready = () => {
  // some code...
}

document.addEventListener('turbolinks:load', ready)
```
I've added the gem `browserify-rails` and add this lines in my initializers:
```
Rails.application.configure do
  config.browserify_rails.commandline_options = '-t [ babelify --presets [env stage-0] ]'
end
```
When I run the command `RAILS_ENV=production bundle exec rails assets:precompile` I get the follow error:

```
rails aborted!
Uglifier::Error: Unexpected token: keyword (const). To use ES6 syntax, harmony mode must be enabled with Uglifier.new(:harmony => true).
```

But if I add in the head of the file `ready.js` any es6 import all works fine:
```
import { Application } from "stimulus"

const ready = () => {
  // some code...
}

document.addEventListener('turbolinks:load', ready)
```

Any idea to force browserify-rails to convert all files, even those that do not have an import?

**Comment by cymen** [comment]
So you could change the source code so it looks for `const` too. However, my recommendation is it use 3 files -- the first has `//= require`, the second is just the skeleton of your app so `import` one or more files and then the third is whatever would have `const ready`. Anything below the second file will be browserified. For best performance, you want that one entry point (for browserified code) of the second file.

Does that make sense? It'll work around your issue and it's clean in the end.

By obligation, just in case, I would also mention that if this is a new project without legacy JavaScript, I highly recommend reading and considering this:

https://github.com/browserify-rails/browserify-rails#should-you-use-this-gem

**Comment by pioz** [comment]
I really prefer browserify over webpacker... much more simple, and has a faster configuration.

**Comment by cymen** [comment]
That may be but this gem, which I've contributed the most to, is not very efficient. So if you wanted to stick with browserify, I'd figured out a way to say run it directly from a Procfile and just skip the whole asset pipeline. That introduces some complexity with deployments.

Of course, if your needs are not so great (not a lot of JavaScript), browserify-rails might work out great for you. All your choice of course I just wanted to let you know up front.

**Comment by pioz** [comment]
> Anything below the second file will be browserified. For best performance, you want that one entry point (for browserified code) of the second file.

What do you think about to browserify anything below the first file inside the `app/assets/javascripts` directory?

**Comment by cymen** [comment]
So this is how it works: the asset pipeline loads each file. It runs browserify-rails as it plugs into the asset pipeline and browserify-rails inspects the file to see if it should run browserify on it.

If yes, it runs browserify and all the code from that file downwards in terms of import/require gets browserfied and the, this is important, the asset pipeline doesn't need to know anything about those lower files.

My advice is to minimize the number of times you jump from asset pipeline to browserify. Partly for performance and partly for complexity -- if you drop down to browserify on two paths and the two paths share common JavaScript modules, you need to mark them as global (I forget the nomenclature in browserify) else they will be loaded separately or duplicated. That is inefficient and also breaks singletons (if you use a module as a singleton pattern).

> What do you think about to browserify anything below the first file inside the app/assets/javascripts directory?

So browserify-rails never gets a plain file. It only gets a stream from the Rails asset pipeline. So it doesn't really know anything about the files except those imported/required within the stream it is given (and of course all the children import/requires).

**Comment by pioz** [comment]
I can force all my js inside `app/assets/javascripts` to be browserified with this config:
```
Rails.application.configure do
  config.browserify_rails.force = ->(file) { file.start_with?(Rails.root.join('app/assets/javascripts').to_s) }
end
```

**Comment by pioz** [comment]
May be change the line

https://github.com/browserify-rails/browserify-rails/blob/fbd8808522978c2a045f5a40a59fd9f2e157693a/lib/browserify-rails/browserify_processor.rb#L92-L94

in
```
def should_browserify?
  !browserified? && (force_browserify? || (in_path? && !browserified? && (commonjs_module?))
end
```
