### ISSUE TITLE
Rails 5.2 support

### ISSUE THREAD

**Issue by lthomaz** [browserify-rails/browserify-rails#215]
Would be great to release a new version with rails 5.2 compability. 
Is it so simple as to increase version in [gemspec](https://github.com/browserify-rails/browserify-rails/blob/master/browserify-rails.gemspec#L22)?

Thanks,

**Comment by cymen** [comment]
Please try browserify-rails 4.3.0.pre with Rails 5.2 if you want to see this released. It is up on rubygems and ready to try.

**Comment by cymen** [comment]
@lthomaz Thanks! Sorry, I was replying more to @pioz and anyone else who came along. I completely understand about weekend :). Best wishes and thanks again.

**Comment by cymen** [comment]
4.3.0.pre seems to be good -- I've released it as 4.3.0 so browserify-rails will work with rails 5.2.

**Comment by cymen** [comment]
Closing as this is resolved.
