### ISSUE TITLE
Cannot get multiple bundles to work

### ISSUE THREAD

**Issue by gabrielecirulli** [browserify-rails/browserify-rails#30]
I'm trying to split my application code and the libraries it uses (React, lodash, and more) into different bundles in order to make the bundle compile faster (right now it takes around 20 seconds every time, which is hard to deal with).

Maybe I don't understand the concept, but I cannot get the mechanism to work.

To start, I have the following structure for my JS:

```
app/assets/javascripts/
  application.js
  dependencies.js
```

Plus of course multiple other files and subdirectories that contain my application's code. All of them are required (either directly or indirectly) from `application.js`.

As I could not understand whether or not it's the correct way to do it, I created `dependencies.js` with the following content:

```javascript
require("lodash");
require("react");
```

It basically requires all of the libraries I want to become external.

I then created `config/browserify.yml`:

```yaml
javascript:
  dependencies:
    require:
      - lodash
      - react

  application:
    external:
      - lodash
      - react
```

As I understand it, the `dependencies.js` file should be requiring all of those libraries and marking them as externally accessible ones, while the `application.js` file should be assuming the presence of the external dependencies and not including them within itself.

Looking at the output when I request `/assets/dependencies.js` in my browser, the generated bundle begins with `require=...`, which should be the right behaviour (since I can now call that function from my other bundle and get those libraries that I need).

The problem is that my `application.js` bundle, which still requires `react` and `lodash` all over the place, also includes the source of those libraries. That's not the expected behaviour, as it should now just expect them to be there rather than bundling them.

Would you be able to tell me what I am doing wrong? 

----

As an aside, I would like to know if the file `dependencies.js` has to be situated at the top level. How would I go about putting it in a subdirectory of `app/assets/javascripts` (e.g. `./system`) and referencing it in `browserify.yml`

**Comment by cymen** [comment]
@gabrielecirulli Wow. That is way too long.

**Comment by cymen** [comment]
@gabrielecirulli I think we are good on this now that browserify-incremental is in. I'll leave the other general performance issue open. Please reopen this if you disagree.
