### ISSUE TITLE
Compress/minify/uglify compiled JavaScript?

### ISSUE THREAD

**Issue by audionerd** [browserify-rails/browserify-rails#36]
When using `browserify-rails`, JavaScript is no longer compressed on precompile in production environments.

I'm not sure why that is.

Should a `browserify` transform like [`uglifyify`](https://github.com/hughsk/uglifyify) be used instead?

**Comment by cymen** [comment]
In the primary project I'm using browserify-rails on, we have this line in `config/environments/production.rb`:

config.assets.js_compressor = Uglifier.new(output: {ascii_only: true, quote_keys: true})

In Rails 4, things changed. More here:

http://www.andylindeman.com/2013/05/08/my-assets-are-no-longer-compressed-in-rails-4-halp.html

**Comment by audionerd** [comment]
@cymen Thanks! I missed that during an upgrade from Rails 3.

It has indeed changed. http://railsdiff.org/diff/v3.2.21/v4.2.0/full/#config-environments-production-rb
