### ISSUE TITLE
is there a way to disable or fix source maps?

### ISSUE THREAD

**Issue by rearadmiral** [browserify-rails/browserify-rails#40]
The docs state that including all the asset paths breaks source maps. Does that mean that source maps don't work at all?

Is there a way to just disable them? In development mode, I'd be fine with just seeing the line that caused the problem and figuring out myself where it came from. Right now it maps all errors to a third-party source file.

**Comment by cymen** [comment]
You should be able to do:

```ruby
config.browserify_rails.source_map_environments = []
```

And that would reset the array to empty.

**Comment by rearadmiral** [comment]
Awesome. That worked.

**Comment by cymen** [comment]
@rearadmiral I am starting to think it would be better if source maps defaulted to off for everything and one had to enable them. Seem reasonable to you? Maybe in the next version we can do that.

**Comment by rearadmiral** [comment]
Sounds good to me
