### ISSUE TITLE
Handle .js.erb files?

### ISSUE THREAD

**Issue by joshfrench** [browserify-rails/browserify-rails#46]
Can you clarify this line from the Readme? "Serve assets with Sprockets."

I assumed that meant files would be run through Sprockets prior to being bundled by Browserify, but files with a `.js.erb` extension don't appear to be served via Sprockets.

Sprockets-style requires work fine (`//= require whatever`) but Browserify-style requires all fail with `Cannot find module 'whatever' from ...`. Is it not possible to have a file processed by Sprockets and Browserify in sequence, or am I just misunderstanding the documentation?

**Comment by cymen** [comment]
Are you 100% certain you have the module installed via npm that you are requiring and that the path is correct? I tried a `.js.erb` on a branch of the sample here:

https://github.com/browserify-rails/multiple-bundles-example/tree/use_js_erb

And it seems to be working without issue. Maybe it isn't quite what you are doing?

**Comment by cymen** [comment]
The commit with the example file is here:

https://github.com/browserify-rails/multiple-bundles-example/commit/ba206785783d68306bb707ef19bd75025c39dd22

**Comment by joshfrench** [comment]
Ah, the error only happens when you attempt to `require` a .js.erb file from another module. See browserify-rails/multiple-bundles-example#1

**Comment by lukewendling** [comment]
@joshfrench Did u figure out how to ```require``` a .js.erb file into another module?

**Comment by joshfrench** [comment]
@lukewendling See https://github.com/browserify-rails/browserify-rails/issues/46, it's not possible to require from Browserify back out to Sprockets.

**Comment by lukewendling** [comment]
Thanks. I originally thought (perhaps like you) that the asset pipeline processed erb (and coffee) files first, and then browserify ran transforms on the output. Appears that's not the case. I also have the same problem on .js.coffee files (without erb). For now, I'm converting the coffee files I want to use as modules via ```require``` to plain .js files.

**Comment by cymen** [comment]
@lukewendling The easiest way to think about it is this: once you get into browserify (the node process) doing the requires, nothing is going through the asset pipeline. So everything has to be compatible with browserify. If you want to use CoffeeScript, that is fine but you have to setup a browserify transform for it -- the asset pipeline is not going to be involved (so it can't convert it).

Most ERB use is to pass values from Ruby to JavaScript. In that case, you need to take a different approach and pass it down when you kick off the browserify JavaScript (so in the view that requires the JavaScript bundle -- that view is ERB -- put your "pass down some data to JS" there).

**Comment by lukewendling** [comment]
Thanks @cymen for the clarification.
