### ISSUE TITLE
when precompiling, module IDs are absolute server paths

### ISSUE THREAD

**Issue by rearadmiral** [browserify-rails/browserify-rails#47]
Maybe I'm missing an obvious configuration option, but it seems when I precompile assets that the module IDs are the absolute file paths of the files on the server that builds the assets.

Is there any way to change them to be numeric, which I thought was the browserify default, or just paths relative to RAILS_ROOT?

For security reasons, I wouldn't be allowed to deploy public files with those paths on them.

**Comment by cymen** [comment]
Yes, good point. This is due to the recent caching merge with browserify-incremental. There is a node module that will fix this (turn them back into numeric ids). In middle of something and can't remember what it is off hand.

**Comment by cymen** [comment]
But we need to use that to fix this -- and figure out how to hook it up so it is done when production assets are built.

**Comment by cymen** [comment]
If this is blocking you, you can revert to an earlier version that does not use browserify-incremental. The fix is to use https://github.com/substack/intreq and was mentioned here https://github.com/browserify-rails/browserify-rails/pull/35.

**Comment by rearadmiral** [comment]
Awesome.  I tried intreq and its sister project bundle-collapser but I couldn't get either incorporated into the commandline_options successfully.  I'll use an earlier version of this gem in the meantime. Thanks so much for the fast response.

**Comment by cymen** [comment]
Unfortunately, I'm finding `browser-unpack` to be exploding with the main build I use this project on (exploding inside of `esprima`). Going to keep on working on it but just FYI it's not quite as easy as I'd hoped.

**Comment by cymen** [comment]
Wahoo! I patched the wrong `browser-unpack` -- turns out with https://github.com/substack/browser-unpack/pull/11 applied, it works correctly.

**Comment by cymen** [comment]
So in holding pattern for https://github.com/substack/browser-unpack/pull/11 to get merged. I'd rather not do a temporary fork so waiting a day or two to see if it gets merged.

**Comment by mlangenberg** [comment]
What's the status of this issue? It looks like substack/browser-unpack#11 has been merged.

Leaking of absolute server paths is kind of blocking for me.

**Comment by cymen** [comment]
@mlangenberg Unfortunately, the path that is supposed to work to remove the module ids doesn't work for me. I found substack also has [intreq](https://github.com/substack/intreq) however that doesn't work either.

The short term solution is to disable browserify-incremental in the production environment. That means asset build times may be a little longer in production but the paths will be anonymized.

**Comment by cymen** [comment]
Whoops, intreq is what was discussed above -- the other potential solution was/is [bundle-collapser](https://github.com/substack/bundle-collapser). It isn't working for me though.

**Comment by mlangenberg** [comment]
>The short term solution is to disable browserify-incremental in the production environment. That means asset build times may be a little longer in production but the paths will be anonymized.

Why would I care about incremental asset building in production? That happens just once on deployment, right?

So removing the dependency on `browserify-incremental` from `package.json` is enough to fix this?

**Comment by cymen** [comment]
Because it speeds up asset compilation even if it is only one pass -- think about it, if two modules require the same module and that module has a typical tree going down with a number of requires, browserify-incremental will cache the first pass of that module so the second time it is required, time will be saved. On the production build for my use, I noticed a speedup of around 60-90 seconds so it is noticeable.

If you want to disable `browserify-incremental` in production, add this line to `config/environments/production.rb`:

```ruby
config.browserify_rails.use_browserifyinc = false
```

**Comment by cymen** [comment]
I should clarify I see those performance differences on Heroku deploys during asset compilation and on CircleCI runs. Both are a little weak in the CPU power (Heroku in particular for the asset build during deployment). So it is tempting to figure out how to make this work with `browserify-incremental` however the pragmatic solution is to have `browserify-rails` disable `browserify-inc` in the production environment.

**Comment by mlangenberg** [comment]
Alright thanks. At least this way sensitive details are not leaking in a JS file. With `RAILS_ENV=production`, does `browserify-rails` automatically set `NODE_ENV=production` for using something like React in production mode?

**Comment by cymen** [comment]
No, `NODE_ENV` would not be updated. But it could be! Would you desire that? And should it set `NODE_ENV` in staging and development too?

**Comment by mlangenberg** [comment]
Well considering the following:

> Development vs. Production Builds
We provide two versions of React: an uncompressed version for development and a minified version for production. The development version includes extra warnings about common mistakes, whereas the production version includes extra performance optimizations and strips all error messages.

For this current project I actually skipped the browserify-rails integration, because I do not want to depend on `node` and `npm` in production, _yet_. (I run `assets:precompile` remotely on deploy) 

However since I noticed a difference between development and production, I ended up generating a production bundle that is checked into version control.

**Comment by cymen** [comment]
I've release 0.8.1 which includes passing through NODE_ENV and disabling browserify-incremental for staging and production builds.

**Comment by cymen** [comment]
Forgot to say please reopen or open a new if things not quite as expected.

**Comment by avk** [comment]
Can someone with some background & experience please document `config.browserify_rails.use_browserifyinc`? The fact that there is a config is mentioned in the README but I had to do Google around just to find this old issue and understand how to turn it back on for production. Really not obvious.

**Comment by cymen** [comment]
@avk What problem are you solving by enabling browserify-incremental in production? It would be good to document it more but it would be great to know what your issue is. It was added via PR from another developer to speed up builds during development. It might help a bit with production builds. Was performance your issue or something about the model names including paths (the issue you're commenting on).

Thanks!

**Comment by avk** [comment]
@cymen this part of the README:

> browserify-incremental is used to cache browserification of CommonJS modules. One of the side effects is that the absolute module path is included in the emitted JavaScript. Most people do not want this for production code so browerify-incremental is current disabled for the production and staging environments. Note that counter-intuitively, browserify-incremental helps even with a single build pass of your code because typically the same modules are used multiple times. So it helps even for say asset compilation on a push to Heroku.

made me want to try enabling browserify-incremental to address recurring High Response Time and Request Timeout alerts on Heroku. I notice these are consistently happening after Heroku cycles a dyno, which causes browserify to execute and slow the first request to a crawl. 

Happy to open another issue if this isn't the right place for that discussion.

**Comment by cymen** [comment]
@avk Ah! Okay, in most cases, for production, the assets are precompiled so while the browserify gem is present in production configuration, it's typically only to precompile the assets and after that, it is no longer invoked. In other words, the typical Rails deploy optimizes assets by building them at deploy time once and then no longer using the asset pipeline. I would recommend that approach with browserify-rails however it if it is working for you as you desire, you can of course not precompile the assets (and it would make sense you would want browserify-incremental enabled then to speed up asset compilation).

**Comment by cymen** [comment]
After rereading that, I see why you want it enabled. I'll update the README.

**Comment by cymen** [comment]
@avk Added a note to the README about running it in production w/ PR https://github.com/browserify-rails/browserify-rails/pull/156.

**Comment by avk** [comment]
@cymen thanks! Really appreciate the explanation.

**Comment by avk** [comment]
> in most cases, for production, the assets are precompiled so while the browserify gem is present in production configuration, it's typically only to precompile the assets and after that, it is no longer invoked.

@cymen unfortunately, this is not what I'm seeing in production. When deploying, `rake precompile:assets` runs and triggers browserify. However, hitting a page with browserified JS once again triggers browserify. Should I open a new issue?

**Comment by cymen** [comment]
@avk That sounds like more of a general assets configuration issue than anything specific to browserify-rails. This Rails doc gives a general overview:

http://guides.rubyonrails.org/asset_pipeline.html#in-production

If you're on Heroku, you likely need to enable the multiple build pack solution and add the nodejs buildback (maybe your asset compile is failing right now). There have been some issues here and a mention in the README regarding Heroku but that again isn't anything specific to browserify-rails. Of course it could be some odd corner case but the way we hook into the asset pipeline basically means we're not driving -- the asset pipeline is.

**Comment by avk** [comment]
@cymen thanks, will investigate further. The asset pipeline config is my suspicion too.

**Comment by avk** [comment]
@cymen right on the money! Seems like [live compilation](http://guides.rubyonrails.org/asset_pipeline.html#live-compilation), enabled by this line:

```ruby
config.assets.compile = true
```

was causing browserify to recompile even after successful `rake assets:precompile`s on production deploys.

**Comment by cymen** [comment]
@avk Ah! That is confusing. I would have expected that to mean the opposite (I thought it did mean the opposite in the past). Thanks for sharing your finding.

**Comment by PikachuEXE** [comment]
Sorry for digging up an old thread

How do I test to know whether "module IDs are absolute server paths" is true for my precompiled JS?

The files are minified so I am not sure what to find
