### ISSUE TITLE
How to get gem to play nicely with react-rails?

### ISSUE THREAD

**Issue by morenoh149** [browserify-rails/browserify-rails#48]
I have a `.js.jsx` file in my assets that is not being required correctly by browserify-rails. https://github.com/reactjs/react-rails#jsx performs on the `assets:precompile` step. When does browserify-rails fire?

directory structure
```
▾ app/
  ▾ assets/
    ▸ images/
    ▾ javascripts/
      ▾ components/
          .gitkeep
          logout_form.js.jsx
          navbar.js.jsx
        application.js
    ▸ stylesheets/
```
```javascript
/* apps/assets/javascripts/application.js */
//= require jquery
//= require jquery-ujs
//= require react
//= require react_ujs
//= require react-bootstrap
//= require socket.io-client/socket.io.js
//= require_tree .

var logoutForm = require('./components/logout_form.js.jsx');
var navbar = require('./components/navbar.js.jsx');
var debug = require('debug')('hermesDragon:client');

debug('loaded npm module using browserify!');
```
*error*
```

BrowserifyRails::BrowserifyError in Homes#index

Showing /Users/harrymoreno/programming/teamrickharry/hermes_dragon/app/views/application/_javascript.html.erb where line #1 raised:

Error while running `/Users/harrymoreno/programming/teamrickharry/hermes_dragon/node_modules/.bin/browserifyinc -d --cachefile="/Users/harrymoreno/programming/teamrickharry/hermes_dragon/tmp/browserify-rails/browserifyinc-cache.json" -o "/Users/harrymoreno/programming/teamrickharry/hermes_dragon/tmp/browserify-rails/output20150226-70503-ct958f" -`:


/Users/harrymoreno/programming/teamrickharry/hermes_dragon/app/assets/javascripts/components/navbar.js.jsx:39
        <LogoutForm
        ^
ParseError: Unexpected token

  (in /Users/harrymoreno/programming/teamrickharry/hermes_dragon/app/assets/javascripts/application.js)

Extracted source (around line #1):

1
2
3
4
5
6
                

	

<%= javascript_include_tag :application %>

<%= javascript_tag do %>
  <%= yield :javascript %>
<% end %>


Trace of template inclusion: app/views/layouts/application.html.erb

Rails.root: /Users/harrymoreno/programming/teamrickharry/hermes_dragon
```

**Comment by cymen** [comment]
You probably want to use a transform for browserify like reactify: https://github.com/andreypopp/reactify

Would that work or do you need to use the same JSX files from browserified and non-browserified code? Even then, I would expect reactify to still work.

I've got another issue to fix but I can get an example of it up on the sample project (might not be until this weekend).

**Comment by morenoh149** [comment]
I solved it by adding a browserify transform `reactify` to my browserify by adding
```
    # Tell browserify to use jsx transform - reactify
    config.browserify_rails.commandline_options = "-t [ reactify --es6 target --es5 ]"
```
to `application.rb`

**Comment by cymen** [comment]
:+1:

**Comment by serv** [comment]
@morenoh149 I'm currently having the same problem.
Can you talk about how your set up reactify on rails to do this?

**Comment by morenoh149** [comment]
@serv what's your error?
this is my `config/application.rb`
```ruby
# Require the gems listed in Gemfile, including any gems
# you've limited to :test, :development, or :production.
Bundler.require(*Rails.groups)

module HermesDragon
  class Application < Rails::Application
    config.i18n.enforce_available_locales = true

    config.action_controller.action_on_unpermitted_parameters = :raise
    # Settings in config/environments/* take precedence over those specified here.
    # Application configuration should go into files in config/initializers
    # -- all .rb files in that directory are automatically loaded.

    # Do not swallow errors in after_commit/after_rollback callbacks.
    config.active_record.raise_in_transactional_callbacks = true

    # Tell browserify to use jsx transform - reactify
    config.browserify_rails.commandline_options =
      '-t [reactify --es6 --extension jsx]'

    # Use delayed_job for ActiveJobs
    config.active_job.queue_adapter = :delayed_job
  end
end
```

**Comment by cymen** [comment]
@morenoh149 Are you using the react-rails gem? I think that is where the confusion is -- I'm guessing you aren't and the answer is to not use the react-rails gem.

**Comment by morenoh149** [comment]
@cymen ah true. Because I use the browserify transform. I have no need to use the react-rails gem. @serv See https://github.com/andreypopp/reactify

**Comment by serv** [comment]
> Because I use the browserify transform. I have no need to use the react-rails gem.

Ah ok! I'll try without it. Thank you

**Comment by piyushchauhan2011** [comment]
@serv @morenoh149 I couldn't make it work.

### I did the following steps:

1. `rails new browserify-test`
2. Updated Gemfile with `browserify-rails` gem. `bundle`
3. Created package.json as specified.
4. `npm install --save browserify browserify-incremental react reactify`
5. In `application.js` file, remove `require_tree .` call and inserted `require main`
6. Updated `config/application.rb` with following code:
`config.browserify_rails.commandline_options = "-t [reactify --extension jsx]"`

main.js
```
var Hello = require('./hello');
console.log(Hello);
```

hello.jsx
```
var React = require('react');
var Hello = React.createClass({
  render: function() {
    return (
      <div>Hello React!</div>
    );
  }
});
module.exports = Hello;
```

### Error
```
events.js:141
      throw er; // Unhandled 'error' event
            ^
Error: Cannot find module './hello' from
```

**Comment by morenoh149** [comment]
try https://github.com/babel/babelify

**Comment by gauravtiwari** [comment]
@piyushchauhan2011 I know it's late, but for anyone else as @morenoh149 suggested : Use `Babel` and this in application.rb

``` javascript
   //Setup browserify with Babel
    config.browserify_rails.commandline_options = "-t babelify --extension=\"es6.js\""
```

then you can require or import like so: 
```javascript
 var Hello = require('./hello.es6.js');
// or
import Hello from './hello.es6.js'
```

**Comment by avk** [comment]
@piyushchauhan2011 in your main.js, you have to use the file extension in require:

`var Hello = require('./hello.es6.js');`

**Comment by avk** [comment]
So is everyone's conclusion here to just not use browserify-rails with react-rails?

**Comment by knagode** [comment]
@gauravtiwari Did you fix your issue? I have the same problem. 

```
events.js:141
      throw er; // Unhandled 'error' event
            ^
Error: Cannot find module './hello' from
```

**Comment by Panczo** [comment]
@knagode I have exactly the same problem. I followed this article [react-rails-browserify](https://medium.com/technically-speaking/rails-react-browserify-e315001d5974#.qxaeasgd4)
For me, now everything works perfect.

**Comment by gauravtiwari** [comment]
@knagode Please refer to this example repo: https://github.com/gauravtiwari/browserify_on_rails

**Comment by dspoonia7** [comment]
Hey @gauravtiwari @avk  
In application.rb, I have added
`config.browserify_rails.commandline_options = "-t babelify --extension=\"es6.js\""`

and in main.js
`var React = window.React = global.React = require('react');`
`var ReactDOM = window.ReactDOM = global.ReactDOM = require('react-dom');`
`window.$ = window.jQuery = require('jquery');`
`require('jquery-ujs');`
`var customComponent = require('./components/ad_details.js.jsx');`

But still I am getting that error 
`ParseError: Unexpected token`

<img width="1265" alt="screen shot 2016-08-02 at 5 15 13 pm" src="https://cloud.githubusercontent.com/assets/8257269/17327540/403c34d8-58d6-11e6-995f-f56116262452.png">

**Comment by gauravtiwari** [comment]
@dspoonia7 Hey, did you add the .babelrc file in the project root? Feel free to checkout this repo: https://github.com/gauravtiwari/browserify_on_rails

**Comment by dspoonia7** [comment]
yes I have .babelrc file in place. It contains
`{  "presets": [ "es2015", "react" ] }`

**Comment by gauravtiwari** [comment]
@dspoonia7 Oh, I see you are using .jsx extension in the filename and in the babelify command option you have give .es6. Please correct the filename extension or change it in application.rb.

```ruby
config.browserify_rails.commandline_options = "-t babelify --extension=\"es6.jsx\""
```

and may be clear the cache: `bundle exec rake tmp:clear` and run the server again.

**Comment by nextofsearch** [comment]
Hi,

I am using Rails 5 with react-rails and browserify-rails gems and I can't figure out how to get image tag working. It seems that browserify-rails take precedence over .js files so there is no chance for Rails process .erb syntax in .js.jsx. Can someone help to use both gems and figure out how to use asset pipeline successfully?
 
https://github.com/reactjs/react-rails/issues/211#issuecomment-259594073

**Comment by Mavvie** [comment]
👍 to @gauravtiwari 

I had really inconsistent/strange behaviour when changing the commandline options. Turns out that removing one of the `tmp/cache` files (specifically, `tmp/cache/browserify-rails/browserifyinc-cache.json`) magically fixed everything for me.

```ruby
# config/application.rb

config.browserify_rails.commandline_options = [
  "-t [ babelify --presets [ react es2015 ] --plugins [ transform-es2015-modules-commonjs ] ]",
]
```

This supports using both jsx and es6 modules (eg. `import`).

**Comment by gauravtiwari** [comment]
@Mavvie Awesome 👍   You can use .babelrc file in root folder to declare plugins and presets. Would clean a lot of options and make it easier to add more in the future. [https://babeljs.io/docs/usage/babelrc/](https://babeljs.io/docs/usage/babelrc/)

**Comment by Mavvie** [comment]
Good idea, thanks! 😃
