### ISSUE TITLE
How to serve bundle only for a specific controller

### ISSUE THREAD

**Issue by morenoh149** [browserify-rails/browserify-rails#51]
In other rails projects you can easily load an asset only for a certain controller http://edgeguides.rubyonrails.org/asset_pipeline.html#controller-specific-assets How can I serve the browserify bundle if a specific controller is responding to the user request?

**Comment by cymen** [comment]
Use the [javascript tag](http://api.rubyonrails.org/classes/ActionView/Helpers/JavaScriptHelper.html#method-i-javascript_tag) in the view for the controller action. There isn't any fancy integration with the scaffolding. PRs are welcome of course.

**Comment by cymen** [comment]
Whoops, that should be [javascript include tag](http://apidock.com/rails/ActionView/Helpers/AssetTagHelper/javascript_include_tag).

**Comment by morenoh149** [comment]
thanks
