### ISSUE TITLE
testing with teaspoon and mocha

### ISSUE THREAD

**Issue by morenoh149** [browserify-rails/browserify-rails#53]
I'm now trying to do testing with the https://github.com/modeset/teaspoon test runner and http://mochajs.org/
```javascript
// /spec/javascripts/example_spec.js
//= require jquery
//= require expect
describe('My great feature', function() {

  it('will change the world', function() {
    expect(true).to.be(true)
    expect(jQuery).to.not.be(undefined)
  })
})
```
I opted to use the sprockets style require `//= require foo` because `var jQuery = require('jquery')` here returns
```bash
ReferenceError: Can't find variable: require
  # example_spec-7c5082a9c51145554112cd53b17714da.js:1
```
But the sprockets style works fine for jquery. It's now choking on the `expect` npm module. I have verified that it's available in `node_modules`. Is the problem that it relies on node's `assert` module? https://www.npmjs.com/package/expect

There should be a way to integrate both as here https://github.com/modeset/teaspoon/wiki/RequireJS-with-Teaspoon are instructions for integrating teaspoon with `requirejs-rails` gem.

**Comment by morenoh149** [comment]
After speaking to the teaspoon maintainer he said I need to make a broserify-rails version of this file https://github.com/modeset/teaspoon/blob/master/app/views/teaspoon/suite/_boot_require_js.html.erb I don't know enough about browserify-rails internals to set this up. Any pointers?

**Comment by cymen** [comment]
I happened to google 'teaspon browserify' and came across this:

https://gist.github.com/th3hunt/7d8673a4571aae6da874

Maybe give that a shot? I [forked the gist in case it disappears](https://gist.github.com/cymen/7ab440c692adc9197ce3).

**Comment by cymen** [comment]
Going to assume this resolves the problem -- please reopen if not.

**Comment by jasonroelofs** [comment]
To help others from spending as much time as I did trying to figure this out, my fix turned out to be a single line addition to my `config/environments/development.rb` file:

`config.browserify_rails.paths << lambda {|p| p.start_with?(Rails.root.join("spec/javascripts").to_s) }`

**Comment by cymen** [comment]
@jasonroelofs That change makes sense -- basically, browserify-rails is getting passed the assets path by Ruby on Rails. Your spec directory is probably not configured to be an asset path (which is logical, I wouldn't configure it to be one either). So with your change, you are telling browerify-rails that in addition to the assets path, also look at this special spec path.

If you can think of how to word this in the README, a PR with a message about it would be more than welcomed. Thank you for sharing the solution.

**Comment by stevenleeg** [comment]
@jasonroelofs could you possibly go into more detail on how to set this up? I'm not entirely sure where I should be putting that browserify boot erb file within my project in order to get this working.

Thanks!

**Comment by jasonroelofs** [comment]
@stevenleeg I ended up not using a custom boot file, as teaspoon does hook right into the Asset pipeline directly. I documented  all of the pieces here: http://collectiveidea.com/blog/archives/2016/03/09/modern-javascript-and-rails/

**Comment by stevenleeg** [comment]
Hmm, I followed your guide and haven't been able to get anything working. Here's what I have so far, if you don't mind helping out a bit:

`config/application.rb`
```ruby
require File.expand_path('../boot', __FILE__)

require 'rails/all'

# Require the gems listed in Gemfile, including any gems
# you've limited to :test, :development, or :production.
Bundler.require(*Rails.groups)

module MyApplication
  class Application < Rails::Application
    ##
    # Browserify rails configuration
    #
    config.browserify_rails.source_map_environments << "development"
    config.browserify_rails.commandline_options = [
      '-t [ babelify --presets [ es2015 react ] --plugins [ transform-object-rest-spread ] ]'
    ]

    unless Rails.env.production?
      Rails.application.config.assets.precompile += %w(spec_helper.js)

      # Enables javascript unit testing with teaspoon
      #config.assets.paths << Rails.root.join('tmp', 'teaspoon', 'assets')
      config.browserify_rails.paths << lambda { |p|
        p.start_with?(Rails.root.join("spec/javascripts").to_s)
      }
    end
  end
end
```

and my test file:

`spec/javascripts/pageEditorReducer_spec.js`
```javascript
import pageEditorReducer from 'reducers/pageEditorReducer'

describe('pageEditorReducer', () =_> {
  it('does stuff', () => {
    expect(true).toEqual(false)
    expect(hello.greet()).toEqual('Hello world')
  })
})
```
(Notice the syntax error on the describe line, as I was trying to see if I could get browserify to explode. The same behavior happens with or without that).

On the console this setup yields:
<img width="618" alt="screen shot 2016-03-25 at 3 03 32 pm" src="https://cloud.githubusercontent.com/assets/141635/14051618/cc899356-f29a-11e5-8fa5-43e3219a02bd.png">

While on the web UI it gives me:
![screen shot 2016-03-25 at 3 04 45 pm](https://cloud.githubusercontent.com/assets/141635/14051643/f09bcbc4-f29a-11e5-87c0-7accea4428db.png)

(with the actual test UI showing 0 examples as well).

Any ideas as to what I could be doing wrong here?

**Comment by jasonroelofs** [comment]
We took this offline. The solution came down to making sure the scripts include `require` or `import` somewhere (this triggers browserify) and make sure you're running `browserify-rails  ~3.x`.

**Comment by noahprince22** [comment]
@stevenleeg Did you ever find the solution? I'm having the same problem
