### ISSUE TITLE
No CHANGELOG

### ISSUE THREAD

**Issue by dbackeus** [browserify-rails/browserify-rails#54]
Please add a CHANGELOG.md or similar and make it part of the gemspec so that users can easily see what's new after a bundle update.

**Comment by cymen** [comment]
I'll do that going forward. Thanks for the push :). I'll leave this open to remember to do that before the next release (should be one shortly to default to disabling browserify-incremental in production environment).

**Comment by dbackeus** [comment]
Awesome!

**Comment by cymen** [comment]
We have a changelog now -- hopefully, it works as expected. It is being included in the gem payload but I'm not sure if it needs to be referenced in some way in the gemspec beyond that -- I couldn't find any details. So I'm going to assume this is all good. I release 0.8.0 and 0.8.1 with changelog updates. I'll assume it is working but please reopen with what you see if it isn't working as expected.
