### ISSUE TITLE
Stale cache breaks browserify-inc?

### ISSUE THREAD

**Issue by joshfrench** [browserify-rails/browserify-rails#55]
This is a weird one and I'm not convinced it's specifically a browserify-rails issue, but 1) I can't reproduce it outside of browserify-rails and 2) it doesn't happen if I disable browserify-incremental, so my first thought is that it has to do with how that's implemented here.

Whenever I modify any JS source, I get a `BrowserifyRails::BrowserifyError` on the next pageload pointing to the following error:
```js
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: ENOENT, open 'foo'
```
where `foo` is whatever the first require in my application happens to be.

Here's a test repo: https://github.com/joshfrench/browserify-rails-demo

To reproduce:

1. git clone && bundle install && npm install.
2. Start Rails server and visit `/`.
3. Modify `application.js` in some way. (It's not sufficient to just resave and change the mtime; the source actually has to differ from what's cached by `browserify-inc`.)
4. Reload page. This is where I experience the error.

Here's what's interesting:

1. If I drop into the Rails console at the error and re-run the underlying `browserify-inc` command (via `Open3`) it succeeds _if_ I modify the arguments.
2. There doesn't seem to be one specific argument that's causing this; rather, _any_ modification is sufficient to fix the problem. If I remove the `--cachefile` option from the `browserify-inc` command, it works. If I remove the `chdir` arg to `Open3`, it works.
3. If I modify the gem source ahead of time with either of those edits, I still get the error.
4. After modifying the gem source, If I drop into the Rails console at the error and re-run the `browserify-inc` command in its _original, unmodified form_ it works again.
6. Reverting `application.js` so that it matches what `browserify-inc` has cached will make the error go away.
5. In other words, it looks as if whenever the cachefile disagrees with what's being served, the command always fails on its initial invocation. Re-invoking it in a different form makes it succeed again.

I'm pretty stumped, and I've been unable to isolate this outside of Rails just using `browserify-incremental` on its own so I thought I'd start here and see if anyone has any thoughts. Thanks!

**Comment by cymen** [comment]
I think it has to do with the paths to the file. Not that you should have to do this but if you use a relative require (`require('./foot')` instead of `require('foo')`), I do not get the error. I was able to reproduce the error you saw -- this is very useful to actually figure out how to fix this.

There is a [note about non-relative paths being dangerous in the README](https://github.com/browserify-rails/browserify-rails#support-for-rails-asset-directories-as-non-relative-module-sources). That is no excuse and it would be nice if they worked well. According to the `browserify-incremental` author, he wrote it for an app that did make use of NODE_PATH. It may be that browserify-rails is not passing a full path somewhere where it should be.

**Comment by joshfrench** [comment]
Here's a missing piece of the puzzle: I'm starting to suspect that the `foo` it can't load is the one listed in `config/browserify.yml`. Removing that also fixes this, and I can't find a combination of relative/non-relative paths that makes both pieces work -- either reloading is broken, or external requires are broken. Maybe it can't reconcile multiple paths to the same file?

**Comment by joshfrench** [comment]
I managed to chase this down to a `browserify-incremental` issue, so I'll close this out and continue debugging over there: jsdf/browserify-incremental#9.
