### ISSUE TITLE
Asset bundle is always named _stream_0.js in the Source Map

### ISSUE THREAD

**Issue by adunkman** [browserify-rails/browserify-rails#62]
It seems that the asset bundle (the file initially loaded from a `<script>`) is always named `_stream_0.js` in the Source Map (the [fixtures](https://github.com/browserify-rails/browserify-rails/search?q=_stream_0&type=Code) also show this). 

Is there a known issue about this, or a reason that you know of? It’d be :heart: :heart: :heart: if it were named the same as the file on disk.

**Comment by cymen** [comment]
This is a side effect of using `browserify-incremental`. In the asset pipeline, you don't get a file to process, you get a stream of content. I don't think there isn't really anything to fix there -- just an oddity. To be honest, unless it is causing bugs, there are more pressing issues!

**Comment by cymen** [comment]
Closing as this is a wontfix from me but PRs are welcome (if they make sense).

**Comment by adunkman** [comment]
:heart:
