### ISSUE TITLE
Warbler/Jruby with `config.assets.initialize_on_precompile = false` causes assets:precompile to skip browserify

### ISSUE THREAD

**Issue by kwhitaker** [browserify-rails/browserify-rails#64]
Title says it all, really.

Our setup requires us to bundle up our app into a jRuby war.  We've got a build script that does the housekeeping for us, including asset precomplilation with the following command:

`jruby -S bundle exec rake assets:precompile`

In the `application.rb`, we have `config.assets.initialize_on_precompile = false`.  If I set it to 'true,' the rake command attempts to connect to a non-existent database (our build server has no active DB).

The problem is, that skips the initializer for browserify-rails, which means our production assets can't utilize the `require` statements.

Is there a workaround for this situation?

**Comment by cymen** [comment]
Looks like it is a common problem and the solution is to register the engine with sprockets:

http://stackoverflow.com/questions/16958352/rails-haml-assets-precompile-with-initialize-on-precompile-false

I don't know off hand the exact syntax you'll need.

**Comment by cymen** [comment]
(for more context, browserify-rails is using Tilt too)
