### ISSUE TITLE
browserify-incremental failure

### ISSUE THREAD

**Issue by lynndylanhurley** [browserify-rails/browserify-rails#65]
The browserify build succeeds initially (after deleting the `tmp` dir and restarting Rails), but fails when a file is changed and the page is reloaded.

The re-builds succeed when I disable browserify-incremental like this:

~~~ruby
config.browserify_rails.use_browserifyinc = false
~~~

##### Notes: 

* I'm using browserify-rails within a Rails engine. I'm not sure if the problem is related to this.
* I haven't been able to get the engine to register the `browserify.yml` file, so I'm passing the `--require` options as `commandline_options` (as seen in the config below).
* I'm using `browserify` version `6.3.4` and `browserify-incremental` version `1.4.0`. I've tried the latest versions of each as well as earlier versions of each and the issue is the same.
* If I revert the change to the `.jsx` file and reload the page, the build is once again successful.

##### package.json

~~~json
{
  "name": "dbx-ui",
  "devDependencies": {
    "browserify": "~> 6.3.4",
    "browserify-incremental": "1.4.0",
    "reactify": "^1.1.0"
  },
  "license": "MIT",
  "engines": {
    "node": ">= 0.12"
  },
  "dependencies": {
    "d3": "^3.5.5",
    "jquery": "1.11.2",
    "metrics-graphics": "^2.3.0",
    "react": "^0.13.1",
    "react-bootstrap": "^0.20.2"
  }
}
~~~

##### engine config:
~~~ruby
    # add engine assets to browserify path
    config.browserify_rails.paths << lambda { |p| p.start_with?(Engine.root.join("app", "assets", "commonjs").to_s)  }

    # contain node modules within engine
    config.browserify_rails.node_bin = Engine.root.join('node_modules', '.bin')

    # transform jsx
    config.browserify_rails.commandline_options = [
      "-t reactify --extension=\".js.jsx\"",
      '-r react',
      '-r jquery',
      '-r dbx_ui_engine/dbx_ui_commonjs',
      '-v'
    ]

~~~

##### successful initial build:

~~~bash
Browserify: /Users/lynn/Code/Healthbox/databoxapi/clients/ui/lib/dbx_ui_engine/node_modules/.bin/browserifyinc -t reactify --extension=".js.jsx
" -r react -r jquery -r dbx_ui_engine/dbx_ui_commonjs -v --list --cachefile="/Users/lynn/Code/Healthbox/databoxapi/tmp/cache/browserify-rails/b
rowserifyinc-cache.json" -o "/Users/lynn/Code/Healthbox/databoxapi/tmp/cache/browserify-rails/output20150408-18766-134fbsb" -
Browserify: /Users/lynn/Code/Healthbox/databoxapi/clients/ui/lib/dbx_ui_engine/node_modules/.bin/browserifyinc -t reactify --extension=".js.jsx
" -r react -r jquery -r dbx_ui_engine/dbx_ui_commonjs -v --cachefile="/Users/lynn/Code/Healthbox/databoxapi/tmp/cache/browserify-rails/browseri
fyinc-cache.json" -o "/Users/lynn/Code/Healthbox/databoxapi/tmp/cache/browserify-rails/output20150408-18766-1056246" -
~~~

##### error (after .jsx file is changed):
~~~bash
Browserify: /Users/lynn/Code/Healthbox/databoxapi/clients/ui/lib/dbx_ui_engine/node_modules/.bin/browserifyinc -t reactify --extension=".js.jsx
" -r react -r jquery -r dbx_ui_engine/dbx_ui_commonjs -v --list --cachefile="/Users/lynn/Code/Healthbox/databoxapi/tmp/cache/browserify-rails/b
rowserifyinc-cache.json" -o "/Users/lynn/Code/Healthbox/databoxapi/tmp/cache/browserify-rails/output20150408-17982-up3cdh" -
Completed 500 Internal Server Error in 796ms

ActionView::Template::Error (Error while running `/Users/lynn/Code/Healthbox/databoxapi/clients/ui/lib/dbx_ui_engine/node_modules/.bin/browseri
fyinc -t reactify --extension=".js.jsx" -r react -r jquery -r dbx_ui_engine/dbx_ui_commonjs -v --list --cachefile="/Users/lynn/Code/Healthbox/d
ataboxapi/tmp/cache/browserify-rails/browserifyinc-cache.json" -o "/Users/lynn/Code/Healthbox/databoxapi/tmp/cache/browserify-rails/output20150
408-17982-up3cdh" -`:

changed files:
/Users/lynn/Code/Healthbox/databoxapi/clients/ui/lib/dbx_ui_engine/app/assets/commonjs/dbx_ui_engine/components/metrics/controller.js.jsx
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: ENOENT, open 'react'
    at Error (native)

~~~

**Comment by jasonwinn** [comment]
Getting very similar issues here, except mine will not even build initially. Had to disable Browserify Incremental as well. Is anyone else experiencing this?

**Comment by cymen** [comment]
@jasonwinn Can you outline how you are using browserify-rails? Do you have multiple bundles? If you want to post your configurations and rails version, that would be awesome. I'd like to reproduce this so I can take a closer look.

@lynndylanhurley I apologize for the slow response. I recently switched employers and have been very busy with that. But I do want to make this work. There are a lot of ways to build the JS and I would expect you've moved on but if you have not, you might consider using browserify directly (with watchify) or webpack. Neither will hook directly into the Rails request cycle (so you can't ensure they'll be in sync with changes from the Rails side) but in practice I think that isn't too big an issue.

**Comment by cymen** [comment]
Also this approach might be worth looking into -- I haven't tried it yet but it is an example of using react with browserify-rails:

https://github.com/timminkov/react-flux-rails

**Comment by jasonwinn** [comment]
@cymen  Thanks for the reply. I am using it with Bundles, Rails 4.2.0 and the Browserify Rails 0.9.1. I did try using an older version of Browserify Rails but no luck. The bundling works fine with incremental disabled, but as soon as incremental is enabled I get a nearly identical error messaging referencing events.js and ENOENT, open 'react'.

I think I may just try setting up browserify directly with watchify and see if it works. I am running inside a Vagrant virtual machine, and I've heard it can be problematic with watchify and webpack's watch, so will have to experiment and see what provides the least headache.

**Comment by cymen** [comment]
@jasonwinn Am I right in assuming the main problem with browserify-incremental disabled is that it is slow? That was the only reason browserify-incremental was added as sometimes the performance without it was sluggish. But if performance is acceptable with it disabled, there is no issue leaving it disabled in terms.

**Comment by cymen** [comment]
@jasonwinn Regarding Vagrant, I had sluggish response while using it on VirtualBox. The tweaks here helped though: https://github.com/mitchellh/vagrant/issues/4204

**Comment by jasonwinn** [comment]
@cymen Correct, it is definitely slower. Maybe around 10 seconds to compile, but it could be the way I had things setup. Still new to all the new frontend module bundlers.

Your Vagrant link sent me on the right direction. I ended up disabling Browserify and setting up Webpack today. The webpack -watch command would not work though. Enabled rsync on VM and now the VM is picking up the changes from the host.

**Comment by cymen** [comment]
@jasonwinn Thanks for confirming it was the slowness. I found on recent maxed out MBP Pros, it wasn't too bad but anything less and it was surprisingly longer to compile. I didn't realize how annoying it was until a coworker showed me. Hopefully, we'll get it figured out but thankfully there are a lot of ways to get the compilation done.

**Comment by jasonwinn** [comment]
@cymen No problem at all. Yeah switching to webpack for now is no big deal, it's amazing how many ways there are to get the compilation done. Using Browserify-Rails was just a nice convenience to keep things simple and in the Rails ecosystem.

Cheers!

**Comment by cymen** [comment]
If there is any interest, browserify-rails 2.x got rid of tilt and uses sprockets directly. It should be much more efficient at detecting when dependencies change so it might be worth a try to see if the performance is better for you.

I'm going to close this issue now.
