### ISSUE TITLE
"devDependencies" need to be "dependencies" on Heroku

### ISSUE THREAD

**Issue by mockdeep** [browserify-rails/browserify-rails#68]
Heroku rejected my push because it ignores `devDependencies` on deploy. Am I missing something?

**Comment by cymen** [comment]
Correct -- the README is wrong. I'll fix it.

**Comment by cymen** [comment]
I updated the README. Thanks!

**Comment by mockdeep** [comment]
Sweet! Should the `coffeeify` one be updated as well?

**Comment by cymen** [comment]
@mockdeep Good call -- I updated it for that too.

**Comment by ankane** [comment]
Fwiw, another option is to use `devDependencies` and set

```sh
heroku config:set NPM_CONFIG_PRODUCTION=false
```

https://devcenter.heroku.com/articles/nodejs-support#devdependencies
