### ISSUE TITLE
reloading asset files if dependency in node_modules changes

### ISSUE THREAD

**Issue by stellard** [browserify-rails/browserify-rails#72]
Hi, I am just wondering if this is the intended behaviour or if my setup is wrong. 

I have put my application specific shared files in node_modules (as advised here https://github.com/substack/browserify-handbook#node_modules) 

This is so I don't have to use relative paths to require them. 

`app/asset/javascripts/test.js`
```javascript
var test = require('test-app')
console.log(test)
````

`node_modules/test-app/index.js`
```javascript
exports = 'this should change'
````

I can change `node_modules/test-app/index.js`, but only when I change `app/asset/javascript/test.js` after the fact does the change show up in the console. 

I tried 
`config.browserify_rails.evaluate_node_modules = true` 
but this seems to have no effect. 

This is a pain because a lot of the time I am working on the test-app module. Is there a better way to achieve this?

**Comment by cymen** [comment]
That is an interesting approach outlined in the handbook. I hadn't read about it before. I do know that the person who wanted `evaluate_node_modules` as an option was using it with [npm link](https://docs.npmjs.com/cli/link). Would that be an option for you?

**Comment by morenoh149** [comment]
I gotta read the handbook :octopus:

**Comment by stellard** [comment]
@cymen, Ive never heard of that but ill check it out thanks.

**Comment by stellard** [comment]
Think this might no longer be an issue. Seems to work in all cases now and still not sure what the issue was. Closing until I can find more info.
