### ISSUE TITLE
Does not work with sass-rails and sprockets

### ISSUE THREAD

**Issue by chrisyeung1121** [browserify-rails/browserify-rails#73]
When i do bundle install

``` shell
Bundler could not find compatible versions for gem "sprockets":
  In Gemfile:
    browserify-rails (~> 0.9) ruby depends on
      sprockets (~> 2.2) ruby

    sass-rails (~> 5.0) ruby depends on
      sprockets (3.0.0)
```

and after downgrading sass-rails to 4.0, it also have problem:

``` shell
Bundler could not find compatible versions for gem "sprockets":
  In Gemfile:
    browserify-rails (~> 0.9) ruby depends on
      sprockets (~> 2.2) ruby

    web-console (~> 2.0) ruby depends on
      sprockets-rails (< 4.0, >= 2.0) ruby depends on
        sprockets (3.0.0)
```

**Comment by thom-nic** [comment]
I hit a similar issue and had to downgrade sprockets.  Should support sprockets 3.x.

**Comment by leishman** [comment]
I am having this problem as well.

**Comment by cymen** [comment]
It turns out to be a bit more complicated than expected:

https://github.com/browserify-rails/browserify-rails/pull/75

It's not that hard to update the dependencies. Everything seems to be okay with basic manual testing. However the automated tests are breaking with the Rails 4 way of doing things. You can try it locally by cloning this repo, checking out the branch from the PR, and updating your project's Gemfile to point to the cloned repo on your local file system:

```
gem 'browserify-rails', path: '../browserify-rails' # nothing else on this line
```

**Comment by leishman** [comment]
Ah interesting. It's alright I ended up just making my javascripts directory an npm project and setting up watchify to recompile a bundled js file that rails serves up.

**Comment by cymen** [comment]
So I think enough needs to change that this might be a bit of a rewrite level change -- basically changing what browserify-rails depends on and bringing over the implementation. For example, we were already using Tilt when I started contributing to this project. Decisions like those could probably be revisited. I was looking at how the coffee-rails gem is implemented as a guideline. I like that it has relatively simple dependencies -- railties and coffee-script. Maybe railties would be all we really need plus of course browserify (and browserify-incremental).

That becomes more of a weekend project and a bit of a big change (definitely seems like a major version change). I'll see if I have time to take a stab at it. But PRs are definitely welcome if anyone else is interested.

@leishman Sounds good -- I'm glad this isn't holding you up. There are a lot of ways to build JavaScript. Hopefully, we'll have a fix soon and we'll keep this issue updated if you're interested in the future.

**Comment by rearadmiral** [comment]
:+1: to this. encountered the same issue trying to upgrade sass after we migrated our app to Rails 4.1

**Comment by thom-nic** [comment]
Any progress on this, maybe a branch I could try out?  I really would prefer to keep everything in the rails asset pipeline, as opposed to adding npm/grunt/gulp/watchify to manage browserified assets.

Thanks!

**Comment by balexand** [comment]
I started by taking the approach suggested above by leishman. Unfortunately, watchify was a bit annoying, and the Rails asset pipeline does not yet support source maps (but it's coming soon).

I ended up switching to webpack, and have had a much better experience. In development, I load the JS bundle directly from the webpack-dev-server. For production, I let webpack build the [minified](http://webpack.github.io/docs/optimization.html), [digested](http://webpack.github.io/docs/long-term-caching.html), bundle into `/public/webpack-assets`. I then use [assets-webpack-plugin](https://github.com/sporto/assets-webpack-plugin) to output a JSON manifest so I can link to the correct file from Rails.

**Comment by cymen** [comment]
@balexand That sounds great. For development when you load from the webpack-dev-server, are you basically going to the webpack-dev-server address in your browser to load the frontend and the frontend is hitting your Rails instance? In other words, if webpack-dev-server starts on say localhost:8080, you just go to http://localhost:8080/ in your browser to load the built front-end?

I'm curious as it sounds like a great solution. I'm no longer working on a Rails project at the moment else I'd spend some time trying it out. I am using webpack (another developer chose it before I came to my current project) and I like it just as much as browserify.

**Comment by balexand** [comment]
@cymen In development, I visit `http://localhost:3000`, which is the Rails server. The rendered HTML includes a script tag pointing directly to the webpack-dev-server on port 8080 (`<script src="http://localhost:8080/bundle.js"></script>`).

The glue code that does this is really hacky since when I started I wasn't sure if I'd stick with webpack. It definitely needs some cleanup. Here's a Gist in case you're interested: https://gist.github.com/balexand/c4977a40a5ebc41cf679

I hope these comments are too off-topic. :)

**Comment by cymen** [comment]
@balexand Thanks -- that makes sense. I was guessing it was one or the other. Not off topic at all. I contribute to this gem a lot but I think for new projects, it would be better to not use this gem. To basically not use the asset pipeline except maybe for deploys. I like your approach.

I think this gem is best suited to get to the point where you can start using a tool like webpack or browserify to build your JavaScript directly. For example, I started on a project where all the JavaScript was using the asset pipeline directly without modules. So lots of globals, jQuery, etc. With this gem, I was able to refactor it all to modules over 6-8 months while actively adding new features too. At that point, I think the pragmatic choice is to no longer use the asset pipeline for JavaScript development.

Of course, everyone is free to do as they see fit! But I'm excited about your approach.

**Comment by cymen** [comment]
To get back to the bigger picture though, I don't have a PR to fix this yet. Unfortunately, I am not using this gem anymore day to day. I hope to fix this issue but I do not have a lot of time. PRs are definitely welcome.

**Comment by cymen** [comment]
@chrisyeung1121 @thom-nic @leishman @rearadmiral This should work with 1.0.0b (b for beta). Can you try 1.0.0b and let me know if you run into any problems? Once we have confirmed it is working as expected, I'll release 1.0.0.

**Comment by cymen** [comment]
I've tested 1.0.0b manually with a new rails app (4.2.1) and it's working great. The default generator for rails used sass-rails 5.0 so it looks like :+1:. My quick test is:

```sh
rails new testing
cd testing
npm install --save browserify browserify-incremental
```
Then add two test JavaScript files:

`app/assets/javascripts/test.js`:
```javascript
var logger = require('./logger');

logger.log('HI!');
```

And:

`app/assets/javascripts/logger.js`:
```javascript
module.exports = function Log(message) {
  console.log(message);
}
```

Then start rails and request `http://localhost:3000/assets/test.js` and verify it is browserified as expected.

I'll release 1.0.0 shortly and we'll be compatible with sass-rails!

**Comment by cymen** [comment]
1.0.0 fixes this issue. Thanks for reporting it!
