### ISSUE TITLE
Source maps broken in mountable engine 'dummy app'

### ISSUE THREAD

**Issue by dmtaub** [browserify-rails/browserify-rails#76]
It works fine when actually mounting my engine, but if i'm using the test/dummy app, the source maps aren't registering. Is there an easy way to get debug output from browserify-rails?

**Comment by cymen** [comment]
Typically, when I'm debugging, I'm using the Ruby or Node one liners to write a string to a file. Most of the processing is done via pipes so it is difficult to debug in some cases and a pragmatic (if ugly) one liner to write the string out to a file in /tmp is easy.

That said, you should be able to modify the config in the dummy to enable source maps for the test environment. Did you try doing that?

**Comment by cymen** [comment]
(whoops, closed by accident)

**Comment by dmtaub** [comment]
i think this might a bug elsewhere in my engine config.. closing
