### ISSUE TITLE
Remove NPM dependency

### ISSUE THREAD

**Issue by BenMorganIO** [browserify-rails/browserify-rails#77]
In a lot of Rails projects, NPM is an added dependency. Is it possible to move the JS required to something ruby based? This way there's not as much complexity.

**Comment by cymen** [comment]
Browserify exists so you can use node modules in the browser. So this project is attached to NPM. So what you've described would be something else.

To me, node modules are to JavaScript as gems are to Ruby.

**Comment by BenMorganIO** [comment]
@cymen Good point. I might be misunderstanding the purpose of this project then.

**Comment by morenoh149** [comment]
purpose of the project is to allow you to use NPM modules in your rails projects.
"*This library adds CommonJS module support to Sprockets (via Browserify).*" - [README.md](https://github.com/browserify-rails/browserify-rails/blob/master/README.md)

**Comment by BenMorganIO** [comment]
@morenoh149 yep, I completely thought this project was solving a different problem...
