### ISSUE TITLE
No easy way to provide for using browserify in a mountable engine / gem but not the host

### ISSUE THREAD

**Issue by dmtaub** [browserify-rails/browserify-rails#79]
I'm using browserify-rails in my gem, and it forces the parent to use it as well with the default paths. In the  in the case that the host app doesn't use it or has a non-default configuration, it may become tricky.

Here's my solution -- engine injects an initializer that does this:
    app.config.browserify_rails.paths  = [] 
    app.config.browserify_rails.paths << lambda { |p| p.start_with?(Engine.root.join("app").to_s) }

There's no way for me to create a gem or engine using browserify-rails that an arbitrary app can mount, since my initializer for configuring browserify-rails is going to depend on whether the parent uses it as well, and AFAIK there's no way to create that conditional.

Perhaps this could be fixed by making all path additions explicit? If there's a way to do it in my engine, I'd be happy for the suggestion.

**Comment by cymen** [comment]
Hrm.. That is an interesting issue. Would it be possible to make a repo with a basic example? There are a couple of places that use `Rails.root`. Would something like this to pass in the root be the solution (and making sure everything uses it)?

http://stackoverflow.com/questions/11615635/rails-root-from-engine

**Comment by cymen** [comment]
I'm going to close this issue as it appears to no longer be active. PRs for such features are of course welcomed however I don't know there is enough interest now that we thankfully have things like webpacker.
