### ISSUE TITLE
warning: circular argument reference - file

### ISSUE THREAD

**Issue by zeisler** [browserify-rails/browserify-rails#84]
Running ruby 2.2.1

~/.rvm/gems/ruby-2.2.1/gems/browserify-rails-0.9.1/lib/browserify-rails/browserify_processor.rb:203: warning: circular argument reference - file

```
def options(file = file)
   options = []
```

The issues here is the ```file = file```. The intention may be to default to nil because I cannot not find another method called file. I would recommend a code change to ```file = nil``` to fix this problem. Will create pull request if needed.

**Comment by cymen** [comment]
@zeisler This should be fixed in 0.9.3 -- another PR changed how that worked. I'll close this but please reopen if that is not the case.
