### ISSUE TITLE
What to do about jQuery / jQuery UI as gems?

### ISSUE THREAD

**Issue by cymen** [browserify-rails/browserify-rails#9]
So a lot of people use the gems for jQuery and jQuery UI. Some use gems that depend on those gems. So the question becomes: what is the ideal way to handle this? Can we avoid duplicate jQuery / jQuery UI? If so, how?

**Comment by audionerd** [comment]
I’ve been testing [`browserify-shim`](https://github.com/thlorenz/browserify-shim), which allows defining an existing global as require-able.

**package.json**
```js
{
  "devDependencies": {
    "browserify-shim": "^3.8.2"
  }
  "browserify-shim": {
    "jquery": "global:$"
  },
}
```
The `global:` prefix tells browserify-shim that it should expose the `$` attached to the `window` as `jquery`.

**application.rb**
```rb
config.browserify_rails.commandline_options = "-t browserify-shim -t coffeeify --extension=\".coffee\""
```

**app.coffee**
```js
Backbone = require("backbone")
Backbone.$ = require("jquery")
```

**app.js (compiled)**
```js
  global.Backbone = require("backbone");
  global.Backbone.$ = (typeof window !== "undefined" ? window.$ : typeof global !== "undefined" ? global.$ : null);
  […]
```

One quirk is that when you change `browserify-shim` config in `package.json`, changes won't be applied until one of the `.coffee` files is also changed. Might be specific to the way I have this setup, not sure.

Reference: https://github.com/thlorenz/browserify-shim/tree/master/examples/expose-jquery

**Comment by morenoh149** [comment]
I haven't run into any gems that require jquery. I was very happy when I removed rails-assets altogether in favor of managing my javascript dependencies via npm.

**Comment by morenoh149** [comment]
I have `var $ = require('jquery')` in the files that need jquery and I've added it to my package.json `    "jquery": "^2.1.3"`.
Can this issue be closed?

**Comment by cymen** [comment]
Seems like this is not a huge issue and is easy to work around.
